import type { Company, Signal, ScoreTier } from "./types";
import { computeSignalScore } from "./scoring";
import { normalizeDomain } from "./domain";

/**
 * Seed/sample data for the dashboard before live sources are wired. Every
 * signal carries an illustrative source_url to model the hard rule. Scores are
 * computed by the real deterministic scorer so the UI reflects actual logic.
 */

let _sid = 0;
function sig(
  company_id: string,
  s: Omit<Signal, "id" | "company_id" | "detected_at"> & { detected_at?: string },
): Signal {
  return {
    id: `sig_${++_sid}`,
    company_id,
    detected_at: s.detected_at ?? "2026-06-20T12:00:00Z",
    ...s,
  };
}

interface Raw {
  id: string;
  name: string;
  website_raw: string;
  description: string;
  subindustry: string;
  ns_industry: string;
  state: string;
  city: string;
  employee_band: string;
  revenue_band: string;
  territory_fit: number;
  score_tier: ScoreTier;
  score_reason: string;
  source: "discovered" | "imported";
  has_new_signal?: boolean;
  signals: (Omit<Signal, "id" | "company_id" | "detected_at"> & { detected_at?: string })[];
  sources: string[];
}

const RAW: Raw[] = [
  {
    id: "c1",
    name: "Cascade Freight Partners",
    website_raw: "https://www.cascadefreight.com",
    description: "Regional less-than-truckload freight and 3PL warehousing operator.",
    subindustry: "Freight & Logistics Services",
    ns_industry: "Transportation / Logistics",
    state: "WA",
    city: "Tacoma",
    employee_band: "201–500",
    revenue_band: "$25M–$50M",
    territory_fit: 0.95,
    score_tier: "A",
    score_reason: "Form D raise corroborated by a Controller hire naming TMS settlements — multiple signals.",
    source: "discovered",
    sources: ["edgar", "indeed"],
    signals: [
      {
        type: "funding",
        strength: "strong",
        weight: 20,
        source_name: "SEC EDGAR",
        source_url: "https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany",
        raw_excerpt: "Form D filed: $8,000,000 equity offering, transportation services.",
        signal_summary: "Filed a Form D for an $8M equity raise.",
        subindustry_relevant: true,
      },
      {
        type: "finance_hire",
        strength: "strong",
        weight: 35,
        source_name: "Indeed",
        source_url: "https://www.indeed.com/jobs?q=controller+TMS",
        raw_excerpt: "Hiring a Controller to own TMS settlements, multi-location billing, month-end close.",
        signal_summary: "Hiring a Controller to own TMS settlements and multi-location billing.",
        subindustry_relevant: true,
      },
    ],
  },
  {
    id: "c2",
    name: "Meridian Staffing Group",
    website_raw: "https://meridianstaffing.io",
    description: "Light-industrial and clerical staffing agency across the Southwest.",
    subindustry: "HR & Staffing",
    ns_industry: "Business Services",
    state: "AZ",
    city: "Phoenix",
    employee_band: "51–200",
    revenue_band: "$10M–$25M",
    territory_fit: 0.9,
    score_tier: "A",
    score_reason: "Acquired a competitor (M&A) plus a back-office QuickBooks→ERP job post.",
    source: "discovered",
    sources: ["news", "linkedin_jobs"],
    signals: [
      {
        type: "m_and_a",
        strength: "strong",
        weight: 20,
        source_name: "PR Newswire",
        source_url: "https://www.prnewswire.com/news-releases/meridian-acquires",
        raw_excerpt: "Meridian Staffing Group announces acquisition of Sun Valley Personnel.",
        signal_summary: "Acquired Sun Valley Personnel.",
        subindustry_relevant: true,
      },
      {
        type: "pain_job_post",
        strength: "medium",
        weight: 15,
        source_name: "LinkedIn Jobs",
        source_url: "https://www.linkedin.com/jobs/view/meridian-back-office",
        raw_excerpt: "Back-office accountant to migrate from QuickBooks to a scalable ERP.",
        signal_summary: "Hiring to migrate off QuickBooks to a scalable ERP.",
        subindustry_relevant: true,
      },
    ],
  },
  {
    id: "c3",
    name: "Northgate Facilities Services",
    website_raw: "https://www.northgatefs.com",
    description: "Commercial janitorial and facilities-management contractor.",
    subindustry: "Facilities Management & Commercial Cleaning",
    ns_industry: "Business Services",
    state: "CO",
    city: "Denver",
    employee_band: "201–500",
    revenue_band: "$10M–$25M",
    territory_fit: 0.88,
    score_tier: "B",
    score_reason: "Single strong vertical signal: Controller hire naming multi-entity close.",
    source: "discovered",
    sources: ["google_jobs"],
    signals: [
      {
        type: "finance_hire",
        strength: "strong",
        weight: 35,
        source_name: "Google Jobs",
        source_url: "https://www.google.com/search?q=northgate+controller",
        raw_excerpt: "Controller to consolidate multi-entity financials and lead month-end close.",
        signal_summary: "Hiring a Controller for multi-entity consolidation and close.",
        subindustry_relevant: true,
      },
    ],
  },
  {
    id: "c4",
    name: "BrightLine Advertising",
    website_raw: "https://brightline.agency",
    description: "Independent full-service advertising and media-buying agency.",
    subindustry: "Advertising & Marketing",
    ns_industry: "Media / Advertising / Publishing",
    state: "TX",
    city: "Austin",
    employee_band: "51–200",
    revenue_band: "$5M–$10M",
    territory_fit: 0.82,
    score_tier: "B",
    score_reason: "New AOR client win plus a billing/traffic finance hire on retainers.",
    source: "discovered",
    sources: ["news", "indeed"],
    signals: [
      {
        type: "new_service",
        strength: "medium",
        weight: 10,
        source_name: "Business Wire",
        source_url: "https://www.businesswire.com/news/brightline-aor",
        raw_excerpt: "BrightLine named agency of record for a national QSR brand.",
        signal_summary: "Won a national AOR account.",
        subindustry_relevant: true,
      },
      {
        type: "finance_hire",
        strength: "medium",
        weight: 20,
        source_name: "Indeed",
        source_url: "https://www.indeed.com/jobs?q=brightline+billing+manager",
        raw_excerpt: "Billing manager for retainer and project revenue recognition (ASC 606).",
        signal_summary: "Hiring a billing manager for retainer/project rev rec.",
        subindustry_relevant: true,
      },
    ],
  },
  {
    id: "c5",
    name: "Summit Legal Solutions",
    website_raw: "https://www.summitlegal.com",
    description: "Mid-size litigation and corporate law firm with three offices.",
    subindustry: "Law Firms & Legal Services",
    ns_industry: "Business Services",
    state: "UT",
    city: "Salt Lake City",
    employee_band: "51–200",
    revenue_band: "$5M–$10M",
    territory_fit: 0.7,
    score_tier: "C",
    score_reason: "Generic growth: general hiring, no vertical-specific pain.",
    source: "discovered",
    sources: ["hiring_monitor"],
    signals: [
      {
        type: "hiring_velocity",
        strength: "medium",
        weight: 10,
        source_name: "Hiring Monitor",
        source_url: "https://boards.greenhouse.io/summitlegal",
        raw_excerpt: "12 open roles posted in the last 30 days across the firm.",
        signal_summary: "Posted 12 roles in 30 days (broad hiring).",
        subindustry_relevant: false,
      },
    ],
  },
  {
    id: "c6",
    name: "Pioneer Moving & Storage",
    website_raw: "https://www.pioneermoving.com",
    description: "Household and commercial moving, storage, and last-mile logistics.",
    subindustry: "Trucking, Moving & Storage",
    ns_industry: "Transportation / Logistics",
    state: "NV",
    city: "Las Vegas",
    employee_band: "51–200",
    revenue_band: "$5M–$10M",
    territory_fit: 0.85,
    score_tier: "B",
    score_reason: "New warehouse + dispatcher/ops hire naming fleet maintenance.",
    source: "discovered",
    sources: ["news", "google_jobs"],
    signals: [
      {
        type: "new_location",
        strength: "medium",
        weight: 12,
        source_name: "Google News",
        source_url: "https://news.google.com/rss/search?q=pioneer+moving+warehouse",
        raw_excerpt: "Pioneer opens a new 80,000 sq ft warehouse in North Las Vegas.",
        signal_summary: "Opened a new 80k sq ft warehouse.",
        subindustry_relevant: true,
      },
      {
        type: "pain_job_post",
        strength: "medium",
        weight: 15,
        source_name: "Google Jobs",
        source_url: "https://www.google.com/search?q=pioneer+dispatcher+fleet",
        raw_excerpt: "Dispatcher/ops lead to manage fleet maintenance and multi-location inventory.",
        signal_summary: "Hiring ops lead for fleet maintenance and multi-location inventory.",
        subindustry_relevant: true,
      },
    ],
  },
  {
    id: "c7",
    name: "Clearwater Consulting",
    website_raw: "https://clearwaterconsulting.co",
    description: "Boutique management-consulting firm focused on operations strategy.",
    subindustry: "Management Consulting",
    ns_industry: "Consulting",
    state: "MN",
    city: "Minneapolis",
    employee_band: "11–50",
    revenue_band: "$5M–$10M",
    territory_fit: 0.78,
    score_tier: "B",
    score_reason: "Pain job post naming utilization, PSA, and project accounting.",
    source: "discovered",
    sources: ["linkedin_jobs"],
    signals: [
      {
        type: "pain_job_post",
        strength: "strong",
        weight: 25,
        source_name: "LinkedIn Jobs",
        source_url: "https://www.linkedin.com/jobs/view/clearwater-finance",
        raw_excerpt: "Finance lead to implement PSA, track utilization and project accounting.",
        signal_summary: "Hiring to implement PSA, utilization, and project accounting.",
        subindustry_relevant: true,
      },
    ],
  },
  {
    id: "c8",
    name: "Atlas Document Management",
    website_raw: "https://www.atlasdocs.com",
    description: "Records storage, scanning, and information-governance services.",
    subindustry: "Information & Document Management",
    ns_industry: "Business Services",
    state: "OR",
    city: "Portland",
    employee_band: "51–200",
    revenue_band: "$10M–$25M",
    territory_fit: 0.8,
    score_tier: "C",
    score_reason: "Generic growth news with no vertical pain.",
    source: "discovered",
    sources: ["news"],
    signals: [
      {
        type: "news",
        strength: "weak",
        weight: 8,
        source_name: "GlobeNewswire",
        source_url: "https://www.globenewswire.com/news-release/atlas-growth",
        raw_excerpt: "Atlas reports a strong year and continued growth.",
        signal_summary: "Reported general year-over-year growth.",
        subindustry_relevant: false,
      },
    ],
  },
  // ── Previously imported (watchlist) ─────────────────────────────────────
  {
    id: "c9",
    name: "Redwood Translation Services",
    website_raw: "https://www.redwoodtranslation.com",
    description: "Enterprise localization and linguistic-services provider.",
    subindustry: "Translation & Linguistic Services",
    ns_industry: "Business Services",
    state: "CA",
    city: "San Jose",
    employee_band: "51–200",
    revenue_band: "$5M–$10M",
    territory_fit: 0.86,
    score_tier: "B",
    score_reason: "New finance hire detected since import.",
    source: "imported",
    has_new_signal: true,
    sources: ["ats_aggregator"],
    signals: [
      {
        type: "finance_hire",
        strength: "medium",
        weight: 20,
        source_name: "Career Sites",
        source_url: "https://jobs.lever.co/redwood/finance-manager",
        raw_excerpt: "Finance manager to own multi-currency billing and revenue recognition.",
        signal_summary: "Hiring a finance manager for multi-currency billing and rev rec.",
        subindustry_relevant: true,
        detected_at: "2026-06-23T09:00:00Z",
      },
    ],
  },
  {
    id: "c10",
    name: "Harbor Marine Logistics",
    website_raw: "https://harbormarine.com",
    description: "Coastal marine shipping and port drayage operator.",
    subindustry: "Marine Shipping & Transportation",
    ns_industry: "Transportation / Logistics",
    state: "AK",
    city: "Anchorage",
    employee_band: "51–200",
    revenue_band: "$10M–$25M",
    territory_fit: 0.84,
    score_tier: "C",
    score_reason: "No new signal since import.",
    source: "imported",
    has_new_signal: false,
    sources: ["ats_aggregator"],
    signals: [
      {
        type: "hiring_velocity",
        strength: "weak",
        weight: 5,
        source_name: "Career Sites",
        source_url: "https://boards.greenhouse.io/harbormarine",
        raw_excerpt: "A handful of operational roles open.",
        signal_summary: "A few operational roles open.",
        subindustry_relevant: false,
      },
    ],
  },
  {
    id: "c11",
    name: "Frontier Carriers",
    website_raw: "https://www.frontiercarriers.com",
    description: "Asset-based regional truckload carrier and fleet operator.",
    subindustry: "Trucking, Moving & Storage",
    ns_industry: "Transportation / Logistics",
    state: "TX",
    city: "Dallas",
    employee_band: "201–500",
    revenue_band: "$25M–$50M",
    territory_fit: 0.93,
    score_tier: "A",
    score_reason: "FMCSA shows a new operating authority and power units growing 40→95, corroborated by a TMS systems hire.",
    source: "discovered",
    sources: ["fmcsa", "indeed"],
    signals: [
      {
        type: "new_entity",
        strength: "strong",
        weight: 22,
        source_name: "FMCSA Census",
        source_url: "https://safer.fmcsa.dot.gov/CompanySnapshot.aspx",
        raw_excerpt: "New operating authority granted; MC number active as of last census update.",
        signal_summary: "Newly granted operating authority (new MC number).",
        subindustry_relevant: true,
      },
      {
        type: "fleet_expansion",
        strength: "strong",
        weight: 14,
        source_name: "FMCSA Census",
        source_url: "https://safer.fmcsa.dot.gov/CompanySnapshot.aspx",
        raw_excerpt: "Power units grew from 40 to 95 and drivers from 38 to 90 over 12 months.",
        signal_summary: "Fleet grew from 40 to 95 power units in a year.",
        subindustry_relevant: true,
      },
      {
        type: "pain_job_post",
        strength: "medium",
        weight: 15,
        source_name: "Indeed",
        source_url: "https://www.indeed.com/jobs?q=frontier+logistics+systems+analyst",
        raw_excerpt: "Logistics systems analyst to implement TMS and driver settlements.",
        signal_summary: "Hiring to implement TMS and driver settlements.",
        subindustry_relevant: true,
      },
    ],
  },
  {
    id: "c12",
    name: "Apex Federal Advisory",
    website_raw: "https://apexfederal.com",
    description: "Management consultancy serving federal and defense agencies.",
    subindustry: "Management Consulting",
    ns_industry: "Consulting",
    state: "CO",
    city: "Colorado Springs",
    employee_band: "51–200",
    revenue_band: "$10M–$25M",
    territory_fit: 0.9,
    score_tier: "A",
    score_reason: "New federal task order (USASpending) plus a Controller hire for DCAA-compliant project accounting.",
    source: "discovered",
    sources: ["usaspending", "linkedin_jobs"],
    signals: [
      {
        type: "gov_contract",
        strength: "strong",
        weight: 18,
        source_name: "USASpending.gov",
        source_url: "https://www.usaspending.gov/award/CONT_AWD_EXAMPLE",
        raw_excerpt: "Awarded a $14M federal task order for advisory services (action_date within window).",
        signal_summary: "Won a $14M federal task order.",
        subindustry_relevant: true,
      },
      {
        type: "finance_hire",
        strength: "strong",
        weight: 35,
        source_name: "LinkedIn Jobs",
        source_url: "https://www.linkedin.com/jobs/view/apex-controller",
        raw_excerpt: "Controller for DCAA-compliant project accounting, ASC 606, and audit-ready close.",
        signal_summary: "Hiring a Controller for DCAA-compliant project accounting.",
        subindustry_relevant: true,
      },
    ],
  },
];

function build(raw: Raw): Company {
  const { score } = computeSignalScore(raw.signals);
  const signals: Signal[] = raw.signals.map((s) => sig(raw.id, s));
  return {
    id: raw.id,
    name: raw.name,
    domain: normalizeDomain(raw.website_raw),
    website_raw: raw.website_raw,
    description: raw.description,
    subindustry: raw.subindustry,
    ns_industry: raw.ns_industry,
    in_territory: true,
    territory_fit: raw.territory_fit,
    source: raw.source,
    status: "new",
    state: raw.state,
    city: raw.city,
    employee_band: raw.employee_band,
    revenue_band: raw.revenue_band,
    signal_score: score,
    score_tier: raw.score_tier,
    score_reason: raw.score_reason,
    has_new_signal: raw.has_new_signal ?? false,
    already_on_netsuite: false,
    starred: false,
    rating: null,
    rating_comment: null,
    sources: raw.sources,
    notes: null,
    first_seen_at: "2026-06-18T12:00:00Z",
    last_updated_at: "2026-06-23T12:00:00Z",
    exported_at: null,
    signals,
  };
}

export const SAMPLE_COMPANIES: Company[] = RAW.map(build);
