import { describe, it } from "vitest";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import fixtures from "../../test/fixtures/registry-nppes-other-name.json";
import { parseCsv } from "@/lib/csv";
import { parseRegistryFinding, stableRegistryJson } from "./registryProfiles";
import { registryOfficialApiCanonicalHash, registryOfficialApiEvidenceHash, type RegistryOfficialApiCorroboration } from "./registryOfficialApi";
import { verifyRegistryNppesOtherName, type RegistryNppesOtherNameEntry } from "./registryNppesOtherName";
import type { CompanyIdentityContext } from "@/lib/companyIdentity";
const sha=(s:string)=>createHash("sha256").update(s).digest("hex"),now=new Date("2026-10-05T03:30:00Z"),at="2026-10-05T03:25:00Z";
function setup(index=0){
 const fixture=structuredClone(fixtures.cases[index]),entry=fixture.entry as RegistryNppesOtherNameEntry,company=fixture.company,context=fixture.context as CompanyIdentityContext;
 const row=parseRegistryFinding(fixture.original,now);
 const proof=()=>{const bare={schema:"official_api_roles_v1" as const,entryId:entry.id,entrySha256:sha(stableRegistryJson(entry)),canonicalIdentitySha256:entry.canonicalIdentitySha256},h=registryOfficialApiEvidenceHash(row,bare);
  return {...bare,reader:{taskId:"/test/dba-final-primary",reviewedAt:at,evidenceSha256:h},reviewer:{taskId:"/test/dba-final-independent",reviewedAt:at,evidenceSha256:h}};};
 const check=(p:RegistryOfficialApiCorroboration=proof(),time=now)=>{const {reader,reviewer,...bare}=p;return verifyRegistryNppesOtherName(row,p,entry,company,context,time,{entrySha256:sha(stableRegistryJson(entry)),canonicalIdentitySha256:registryOfficialApiCanonicalHash(company,context),evidenceSha256:registryOfficialApiEvidenceHash(row,bare),canonicalDomain:company.domain});};
 const rebind=()=>entry.canonicalIdentitySha256=registryOfficialApiCanonicalHash(company,context);
 return {entry,company,context,row,proof,check,rebind};
}
type F=ReturnType<typeof setup>;
function mutate(part:RegistryNppesOtherNameEntry["source"]["main"],values:Record<string,string>){const cells=parseCsv(part.rawRow)[0];for(const [key,value]of Object.entries(values)){const i=part.headers.indexOf(key);assert(i>=0);cells[i]=value;}part.rawRow=cells.map(x=>'"'+x.replaceAll('"','""')+'"').join(',')+'\n';part.rawRowSha256=sha(part.rawRow);}
function main(f:F,values:Record<string,string|undefined>){mutate(f.entry.source.main,values as Record<string,string>);f.row.evidence=f.row.profile.provenance.quote=f.entry.source.main.rawRow;f.row.profile.provenance.rowSha256=f.entry.target.rowSha256=f.entry.source.main.rawRowSha256;f.entry.target.evidenceSha256=sha(f.row.evidence);}
describe("retained NPPES organization DBA",()=>{
 for(const index of [0,1])it("accepts complete retained case "+index+" without changing legal identity/raw fields",()=>{const f=setup(index),before=JSON.stringify(f.row),v=f.check();assert.equal(v.method,"reviewed_official_registration_history");assert.equal(JSON.stringify(f.row),before);const d=v.officialHistory!.nppesOrganizationDba as Record<string,unknown>;assert.equal(d.mainOtherName,"<UNAVAIL>");assert.equal(d.mainOtherNameType,"6");assert.equal(d.legalName,f.row.profile.identity.legalName);assert.equal((d.otherNameRows as unknown[]).length,index===0?1:2);});
 it("uses exact canonical address sourceId without requiring a new own-site field",()=>{const f=setup();f.entry.anchor={mode:"dba_canonical_address",originalAddressRole:"provider_practice",sourceId:f.context.addresses[0].sourceId};delete f.entry.website;assert.equal(f.check().method,"reviewed_official_registration_history");});
 it("has no company allowlist",()=>{const f=setup();f.company.id=f.row.companyId=f.entry.companyId="11111111-1111-4111-8111-111111111111";f.company.netsuite_internal_id=f.row.internalId=f.entry.internalId="123456";f.entry.id="TEST-OTHER-COMPANY";f.rebind();f.check();});
 const negatives:Record<string,(f:F)=>void>={
  wrongCompany:f=>f.company.id="other",wrongInternal:f=>f.row.internalId="other",canonicalPin:f=>f.entry.canonicalIdentitySha256="0".repeat(64),
  missingNameToken:f=>{f.company.name="Care";f.rebind();},extraLegalSuffix:f=>{f.company.name+=" LLC";f.rebind();},knownAliasConflict:f=>{f.context.aliases.push("Other LLC");f.rebind();},
  originalFact:f=>f.row.profile.facts[0].value="1111111111",originalDate:f=>f.row.profile.sourceAsOf="2026-09-12",originalEvidence:f=>f.row.evidence+=" ",originalIdentity:f=>f.row.profile.identity.addressLine2="Suite 17",
  differentNpi:f=>mutate(f.entry.source.otherNames[0],{NPI:"1999999999"}),type4FormerLegal:f=>mutate(f.entry.source.otherNames[0],{"Provider Other Organization Name Type Code":"4"}),type5Other:f=>mutate(f.entry.source.otherNames[0],{"Provider Other Organization Name Type Code":"5"}),type6MainPlaceholder:f=>mutate(f.entry.source.otherNames[0],{"Provider Other Organization Name Type Code":"6"}),
  otherNameMissingWord:f=>mutate(f.entry.source.otherNames[0],{"Provider Other Organization Name":"Placement"}),invalidDate:f=>mutate(f.entry.source.otherNames[0],{"Created Date":"02/30/2018"}),futureDate:f=>mutate(f.entry.source.otherNames[0],{"Created Date":"10/01/2026"}),
  missingOtherRows:f=>f.entry.source.otherNames=[],duplicateOtherRow:f=>f.entry.source.otherNames.push(structuredClone(f.entry.source.otherNames[0])),
  rawHash:f=>f.entry.source.otherNames[0].rawRowSha256="0".repeat(64),memberSnapshot:f=>f.entry.source.otherNames[0].member="othername_pfile_20050523-20260914.csv",missingMemberHash:f=>f.entry.source.otherNames[0].memberSha256="",invalidMemberCrc:f=>f.entry.source.otherNames[0].memberCrc32="",missingHeaderReceipt:f=>f.entry.source.otherNames[0].headerReceiptSha256="0".repeat(64),missingRecordPosition:f=>f.entry.source.otherNames[0].dataRecordNumber=0,
  changedHeaders:f=>{f.entry.source.otherNames[0].headers[1]="Other";f.entry.source.otherNames[0].headersSha256=sha(stableRegistryJson(f.entry.source.otherNames[0].headers));},rawHeaderHash:f=>f.entry.source.otherNames[0].headerRawCsvSha256="0".repeat(64),truncatedRow:f=>{const p=f.entry.source.otherNames[0];p.rawRow='"1255705703"\n';p.rawRowSha256=sha(p.rawRow);},
  sourceSpoof:f=>f.entry.source.requestedUrl="https://evil.test/nppes.zip",incompleteArchive:f=>f.entry.source.completeMemberStreamsAndCrcVerified=false as true,missingArchiveHash:f=>f.entry.source.archiveSha256="",sourceAfterExtraction:f=>f.entry.source.extractedAt="2026-09-01T00:00:00Z",
  codebookWrongPdf:f=>f.entry.source.codebook.pdfSha256="0".repeat(64),codebookWrongMeaning:f=>f.entry.source.codebook.meaning="Former Legal Business Name" as "Doing Business As",codebookTextChanged:f=>f.entry.source.codebook.pageText+="changed",codebookReceiptMissing:f=>f.entry.source.codebook.receiptSha256="",
  siteWrongUnit:f=>f.entry.website!.address.addressLine1="3691 Via Mercado #17",siteUnitAbsent:f=>f.entry.website!.address.addressLine1="3691 Via Mercado",siteWrongZip:f=>f.entry.website!.address.postalCode="91942",siteForeignCountry:f=>f.entry.website!.address.countryCode="CA" as "US",siteMissingCountry:f=>f.entry.website!.address.countryCode="" as "US",siteWrongCity:f=>f.entry.website!.address.city="San Diego",siteWrongState:f=>f.entry.website!.address.state="CO",
  siteWrongPhone:f=>f.entry.website!.phoneAsDisplayed="(619) 660-8815",sitePhoneNotInQuote:f=>f.entry.website!.contactQuote="Care Placement",siteWrongSubject:f=>f.entry.website!.subject="Different Placement",siteMissingSubject:f=>f.entry.website!.subjectQuote="Privacy Policy",siteSubjectSubstring:f=>{const s=f.entry.website!;s.subjectQuote="NotCare Placement";s.text+=" "+s.subjectQuote;s.textSha256=sha(s.text);},siteWrongDomain:f=>f.entry.website!.finalUrl="https://example.com/",siteSubdomain:f=>f.entry.website!.finalUrl="https://wrong.careplacement.com/",siteBadHop:f=>f.entry.website!.hops[0].url="https://evil.test/",siteNotComplete:f=>f.entry.website!.status=206,siteTextChanged:f=>f.entry.website!.text+="changed",siteNoHtmlPin:f=>f.entry.website!.htmlSha256="",
  sameSourceActor:f=>f.entry.sourceReviewer.taskId=f.entry.sourceReader.taskId,sourceBeforeExtraction:f=>f.entry.sourceReader.reviewedAt="2026-10-01T00:00:00Z",sourceMissingReceipt:f=>f.entry.sourceReviewer.receiptSha256="",sameOriginalActor:f=>f.entry.originalReviews.independent.taskId=f.entry.originalReviews.primary.taskId,missingOriginalPacket:f=>f.entry.originalReviews.packetSha256="",wrongAddressRole:f=>f.entry.anchor.originalAddressRole="mailing" as "provider_practice",
 };
 for(const [name,mutation]of Object.entries(negatives))it("rejects "+name+" even with newly bound catalog/final evidence",()=>{const f=setup();mutation(f);assert.throws(()=>f.check());});
 for(const [name,delta]of Object.entries({type1:{"Entity Type Code":"1"},replacement:{"Replacement NPI":"1255705704"},individual:{"Provider First Name":"Jane"},parentConflict:{"Parent Organization LBN":"Different Inc"},subpartMissingParent:{"Is Organization Subpart":"Y"},subpartUnknown:{"Is Organization Subpart":""},mainAliasConflict:{"Provider Other Organization Name":"Other Brand","Provider Other Organization Name Type Code":"3"},mainKnownNonDba:{"Provider Other Organization Name":"Care Placement","Provider Other Organization Name Type Code":"4"},mainPracticeAddress:{"Provider Second Line Business Practice Location Address":"Suite 17"}}))it("rejects "+name+" despite refreshing raw target hashes",()=>{const f=setup();main(f,delta);assert.throws(()=>f.check());});
 for(const mode of ["sourceId","sourceKind","missingUnit","duplicate","missing","badDate"])it("rejects canonical anchor "+mode,()=>{const f=setup();f.entry.anchor={mode:"dba_canonical_address",originalAddressRole:"provider_practice",sourceId:f.context.addresses[0].sourceId};delete f.entry.website;
  if(mode==="sourceId")f.entry.anchor.sourceId="wrong";if(mode==="sourceKind")f.context.addresses[0].sourceKind="other" as "netsuite_record";if(mode==="missingUnit")f.context.addresses[0].addressLine1="3691 Via Mercado";if(mode==="duplicate")f.context.addresses.push(structuredClone(f.context.addresses[0]));if(mode==="missing")f.context.addresses=[];if(mode==="badDate")f.context.addresses[0].capturedAt="unknown";f.rebind();assert.throws(()=>f.check());});
 for(const mode of ["sameActor","badActor","early","stale","future","wrongHash","extraWitness","changedDetail"])it("rejects final "+mode,()=>{const f=setup(),p=f.proof();if(mode==="sameActor")p.reviewer.taskId=p.reader.taskId;if(mode==="badActor")p.reviewer.taskId="";if(mode==="early")p.reader.reviewedAt="2026-10-01T00:00:00Z";if(mode==="future")p.reviewer.reviewedAt="2026-11-01T00:00:00Z";if(mode==="wrongHash")p.reviewer.evidenceSha256="0".repeat(64);if(mode==="extraWitness")Object.assign(p.reviewer,{claimed:true});if(mode==="changedDetail")f.row.detail+="changed";assert.throws(()=>f.check(p,mode==="stale"?new Date("2026-10-20T00:00:00Z"):now));});
 it("does not drop one of two Feld reported dates or confuse Created Date with enumeration",()=>{const f=setup(1),v=f.check(),rows=(v.officialHistory!.nppesOrganizationDba as {otherNameRows:{createdDate:string}[]}).otherNameRows;assert.deepEqual(rows.map(r=>r.createdDate),["07/10/2018","07/17/2018"]);});
});
