import {createHash} from 'node:crypto';
import {describe,it,expect,vi} from 'vitest';
import fixture from '../../test/fixtures/registry-official-gbsm-conference.json';
import catalog from './registryOfficialDocumentEntries.json';
import {parseRegistryFinding,stableRegistryJson} from './registryProfiles';
const sha=(s:string)=>createHash('sha256').update(s).digest('hex'),now=new Date('2026-10-02T10:00:00Z'),at='2026-10-02T09:00:00Z';
async function setup(){
 const f:any=structuredClone(fixture),entry=f.entry,entries=[...structuredClone(catalog.entries.slice(0,12)),entry];
 vi.resetModules();vi.doMock('./registryOfficialDocumentEntries.json',()=>({default:{schema:'reviewed_official_document_entries_v1',entries}}));
 const module=await import('./registryOfficialDocuments'),route=await import('./registryOfficialHistory'),row=parseRegistryFinding(f.finding,now);
 const proof=()=>{const bare={schema:'official_document_roles_v1' as const,entryId:entry.id,entrySha256:module.registryOfficialDocumentEntry(entry.id).sha256,canonicalIdentitySha256:entry.canonicalIdentitySha256},evidenceSha256=module.registryOfficialDocumentEvidenceHash(row,bare);return {...bare,reader:{taskId:'/test/gbsm-primary',reviewedAt:at,evidenceSha256},reviewer:{taskId:'/test/gbsm-independent',reviewedAt:at,evidenceSha256}};};
 const rebind=()=>{for(const p of entry.conference.pages)p.textSha256=sha(p.text);entry.sources[0].text=entry.conference.pages.map((p:any)=>`--- PHYSICAL PAGE ${p.page} ---\n${p.text}`).join('\n\n');entry.sources[0].textSha256=sha(entry.sources[0].text);};
 return {...f,entry,entries,row,module,proof,rebind,check:(p=proof())=>route.verifyRegistryOfficialHistory(row,p,f.company,f.context,now)};
}
describe('finite GBSM university conference contact',()=>{
 it('admits only the historical contact association through the unchanged publisher route',async()=>{const f=await setup(),before=JSON.stringify(f.row),r=f.check();expect(r.method).toBe('reviewed_official_registration_history');expect(JSON.stringify(f.row)).toBe(before);expect(f.context.addresses).toEqual([]);expect(f.entry.conference.companyDisplay).toBe('GBSM Consulting');expect(f.entry.legalName).toBe('GBSM, Inc.');expect(f.entry.sources[0].completeRead).toBe(false);expect(f.entry.conference.publicationDate).toBeNull();expect(f.entry.conference.registeredOfficeClaim).toBe(false);expect(Object.hasOwn(f.row.profile.identity,'countryCode')).toBe(false);expect(JSON.parse(f.row.evidence.split('\n')[0]).country).toBe('United States');});
 it('preserves all twelve earlier entries, five held keys and three earlier accepted mappings',async()=>{const f=await setup();expect(f.entries).toHaveLength(13);for(const e of catalog.entries.slice(0,12))expect(f.module.registryOfficialDocumentEntry(e.id).sha256).toBe(sha(stableRegistryJson(e)));expect(fixture.heldProfileKeys).toHaveLength(5);expect(fixture.previouslyAcceptedProfileKeys).toHaveLength(3);for(const key of fixture.heldProfileKeys)expect(f.entries.some((x:any)=>('registry:'+x.target.dataset+':'+x.target.recordId)===key)).toBe(false);});
 it.each(['kind','url','requested','hops','status','mime','text_hash','body_hash','source_date','date_text','whole_read','selected_read','excerpt_pin'])('rejects capture/read scope mutation %s',async key=>{const f=await setup(),s=f.entry.sources[0];if(key==='kind')s.kind='company_pdf';if(key==='url')s.url=s.url.replace('law.du.edu','example.com');if(key==='requested')s.requestedUrl=s.url;if(key==='hops')s.hops=[{url:s.url,status:200}];if(key==='status')s.status=206;if(key==='mime')s.contentType='text/html';if(key==='text_hash')s.textSha256='0'.repeat(64);if(key==='body_hash')s.bodySha256='';if(key==='source_date')s.sourceDate='2013-01-01';if(key==='date_text')s.sourceDateText='2013';if(key==='whole_read')s.completeRead=true;if(key==='selected_read')s.selectedExcerptCompleteRead=false;if(key==='excerpt_pin')s.originalSourcePin='0'.repeat(64);expect(()=>f.check()).toThrow();});
 it.each(['count','whole_read','selected_read','missing','order','image','page_hash','page_title','page_header','text_only_block','duplicate_block'])('requires full exact selected page context %s',async key=>{const f=await setup(),c=f.entry.conference;if(key==='count')c.fullDocumentPages=2;if(key==='whole_read')c.fullDocumentRead=true;if(key==='selected_read')c.selectedPagesCompleteRead=false;if(key==='missing')c.pages.shift();if(key==='order')c.pages.reverse();if(key==='image')c.pages[1].visualSha256='';if(key==='page_hash')c.pages[1].textSha256='0'.repeat(64);if(key==='page_title'){c.pages[0].text=c.pages[0].text.replace('2013 ROCKY','2014 ROCKY');f.rebind();}if(key==='page_header'){c.pages[1].text=c.pages[1].text.replace('Page 7','Page 8');f.rebind();}if(key==='text_only_block'){f.entry.sources[0].text=c.contactBlock;f.entry.sources[0].textSha256=sha(c.contactBlock);}if(key==='duplicate_block'){c.pages[1].text+='\r\n'+c.contactBlock;f.rebind();}expect(()=>f.check()).toThrow();});
 it.each(['office','current','employment','continuous','financial','publication','effective','role','company','person','email','email_subdomain','phone','2020s','unit_missing','unit_other','street','city','zip','identity_page','adjacent_attendee'])('rejects role or identity substitution %s',async key=>{const f=await setup(),c=f.entry.conference;if(key==='office')c.registeredOfficeClaim=true;if(key==='current')c.currentAddressClaim=true;if(key==='employment')c.currentEmploymentClaim=true;if(key==='continuous')c.continuousOccupancyClaim=true;if(key==='financial')c.financialInference=true;if(key==='publication')c.publicationDate='2013-01-01';if(key==='effective')c.addressEffectiveDate='2013-01-01';if(key==='role')c.role='registered_office';if(key==='company')c.companyDisplay='GBSM, Inc.';if(key==='person')c.person='Davis, Anna';if(key==='email')c.email='alex@example.com';if(key==='email_subdomain')c.email='alexdavis@gbsm.com.evil.test';if(key==='phone')c.phoneLiteral='303-825-6101';if(key==='2020s')c.address.addressLine1='600 17th Street, Suite 2020s';if(key==='unit_missing')c.address.addressLine1='600 17th Street';if(key==='unit_other')c.address.addressLine2='Suite 550';if(key==='street')c.address.addressLine1='535 16th Street, Suite 620';if(key==='city')c.address.city='Aurora';if(key==='zip')c.address.postalCode='80220';if(key==='identity_page')c.identityPage=1;if(key==='adjacent_attendee'){c.pages[1].text=c.pages[1].text.replace(c.contactBlock+'\r\nDavis, Anna',c.contactBlock+'\r\nDifferent boundary');f.rebind();}expect(()=>f.check()).toThrow();});
 it.each(['other_profile','other_company','canonical_alias','canonical_address','canonical_domain','original_same_actor','source_same_actor','source_early','source_missing_pin','final_same_actor','final_early','final_hash','profile_country_added','detail'])('preserves exact target and actual witness fencing %s',async key=>{const f=await setup(),e=f.entry,p=f.proof();if(key==='other_profile')e.target.recordId='1352717:1088072';if(key==='other_company')e.companyId='00000000-0000-4000-8000-000000000000';if(key==='canonical_alias')f.context.aliases.push('Different Inc.');if(key==='canonical_address')f.context.addresses.push({...e.targetAddress,capturedAt:at,sourceKind:'netsuite_record',sourceId:'fake'});if(key==='canonical_domain')f.company.domain='different.test';if(key==='original_same_actor')e.originalReviews.independent.taskId=e.originalReviews.primary.taskId;if(key==='source_same_actor')e.sourceReviewer.taskId=e.sourceReader.taskId;if(key==='source_early')e.sourceReviewer.reviewedAt='2026-10-01T00:00:00Z';if(key==='source_missing_pin')e.sourceReviewer.receiptSha256='';if(key==='final_same_actor')p.reviewer.taskId=p.reader.taskId;if(key==='final_early')p.reader.reviewedAt='2026-10-02T07:00:00Z';if(key==='final_hash')p.reader.evidenceSha256='0'.repeat(64);if(key==='profile_country_added')f.row.profile.identity.countryCode='US';if(key==='detail')f.row.detail='Changed';expect(()=>f.check(key.startsWith('final_')||key==='detail'?p:undefined)).toThrow();});
});
