import { createHash } from "node:crypto";
import { describe,expect,it,vi } from "vitest";
import fixture from "../../test/fixtures/registry-official-redsky-court.json";
import catalog from "./registryOfficialDocumentEntries.json";
import { parseRegistryFinding,stableRegistryJson } from "./registryProfiles";
const sha=(s:string)=>createHash("sha256").update(s).digest("hex"),now=new Date("2026-10-02T09:00:00Z"),at="2026-10-02T08:55:00Z";
async function setup(index=0){
 const f:any=structuredClone(fixture.cases[index]),entry=f.entry,entries=[...structuredClone(catalog.entries.slice(0,6)),...structuredClone(fixture.cases).map((x,i)=>i===index?entry:x.entry)];
 vi.resetModules();vi.doMock("./registryOfficialDocumentEntries.json",()=>({default:{schema:"reviewed_official_document_entries_v1",entries}}));
 const module=await import("./registryOfficialDocuments"),route=await import("./registryOfficialHistory"),row=parseRegistryFinding(f.finding,now);
 const proof=()=>{const bare={schema:"official_document_roles_v1" as const,entryId:entry.id,entrySha256:module.registryOfficialDocumentEntry(entry.id).sha256,canonicalIdentitySha256:entry.canonicalIdentitySha256},evidenceSha256=module.registryOfficialDocumentEvidenceHash(row,bare);return {...bare,reader:{taskId:"/test/redsky-primary",reviewedAt:at,evidenceSha256},reviewer:{taskId:"/test/redsky-independent",reviewedAt:at,evidenceSha256}};};
 const rebind=()=>{for(const p of entry.court.pages)p.textSha256=sha(p.text);entry.sources[0].text=entry.court.pages.map((p:any)=>`--- PHYSICAL PAGE ${p.page} ---\n${p.text}`).join("\n\n");entry.sources[0].textSha256=sha(entry.sources[0].text);};
 return {...f,entry,entries,row,module,proof,rebind,check:(p=proof())=>route.verifyRegistryOfficialHistory(row,p,f.company,f.context,now)};
}
describe("finite court-filed counterparty contact excerpt",()=>{
 it.each([0,1,2,3,4,5])("admits historical identity only for exact selected original %i",async i=>{const f=await setup(i),before=JSON.stringify(f.row),r=f.check();expect(r.method).toBe("reviewed_official_registration_history");expect(JSON.stringify(f.row)).toBe(before);expect(f.context.addresses).toEqual([]);expect(f.context.aliases).toEqual([]);expect(f.entry.sources[0].completeRead).toBe(false);expect(f.entry.sources[0].selectedExcerptCompleteRead).toBe(true);expect(f.entry.court.addressEffectiveDate).toBeNull();expect(f.entry.court.counterpartyBankruptcyClaim).toBe(false);expect(f.entry.court.row.debtor).toBe("Monster Worldwide, LLC");});
 it("retains six existing entries, nine holds, six debtor rows and five filings",async()=>{const f=await setup();for(const e of catalog.entries.slice(0,6))expect(f.module.registryOfficialDocumentEntry(e.id).sha256).toBe(sha(stableRegistryJson(e)));expect(f.entries).toHaveLength(12);expect(fixture.heldOriginalProfileKeys).toHaveLength(9);expect(new Set(fixture.cases.map(x=>x.entry.target.recordId.split(":" )[0])).size).toBe(5);for(const key of fixture.heldOriginalProfileKeys)expect(()=>f.module.registryOfficialDocumentEntry(key)).toThrow();});
 it.each([4,5])("preserves omitted original country in IRS-lien original %i",async i=>{const f=await setup(i);expect(Object.hasOwn(JSON.parse(f.row.evidence.split("\n")[0]),"country")).toBe(false);expect(Object.hasOwn(f.row.profile.identity,"countryCode")).toBe(false);expect(f.entry.originalCountry.rawCountry).toBeNull();const b=f.row.evidence;f.check();expect(f.row.evidence).toBe(b);expect(Object.hasOwn(f.row.profile.identity,"countryCode")).toBe(false);});
 it.each(["kind","host","request","hops","status","mime","hash","source_date","source_date_text","full_read","excerpt_read","source_pin"])("rejects changed capture or read-scope %s",async k=>{const f=await setup(),s=f.entry.sources[0];if(k==="kind")s.kind="company_pdf";if(k==="host")s.url=s.url.replace("casedocs.omniagentsolutions.com","evil.test");if(k==="request")s.requestedUrl="https://evil.test/a.pdf";if(k==="hops")s.hops=[{url:s.url,status:200}];if(k==="status")s.status=206;if(k==="mime")s.contentType="text/html";if(k==="hash")s.textSha256="0".repeat(64);if(k==="source_date")s.sourceDate="2025-07-15";if(k==="source_date_text")s.sourceDateText="July 14, 2025";if(k==="full_read")s.completeRead=true;if(k==="excerpt_read")s.selectedExcerptCompleteRead=false;if(k==="source_pin")s.originalSourcePin="0".repeat(64);expect(()=>f.check()).toThrow();});
 it.each(["total","full_read","partial_read","missing_page","duplicate_page","reorder","page_hash","visual","extraction","page_label","omitted_text","notice_context"])("requires complete pinned selected context %s",async k=>{const f=await setup(),c=f.entry.court;if(k==="total")c.fullDocumentPages=1077;if(k==="full_read")c.fullDocumentRead=true;if(k==="partial_read")c.selectedPagesCompleteRead=false;if(k==="missing_page")c.pages.splice(2,1);if(k==="duplicate_page")c.pages[3].page=3;if(k==="reorder")c.pages.reverse();if(k==="page_hash")c.pages[0].textSha256="0".repeat(64);if(k==="visual")c.pages[0].visualSha256="";if(k==="extraction")c.excerptReceiptSha256="0".repeat(64);if(k==="page_label"){c.pages[8].text=c.pages[8].text.replace("Page 633 of 1077","Page 633 of 1076");f.rebind();}if(k==="omitted_text"){f.entry.sources[0].text=c.pages[8].text;f.entry.sources[0].textSha256=sha(f.entry.sources[0].text);}if(k==="notice_context"){c.pages[2].text=c.pages[2].text.replace("does not constitute an admission","does constitute an admission");f.rebind();}expect(()=>f.check()).toThrow();});
 it.each(["role","current_address","effective_date","contract_date","bankruptcy","assignment","finance","case","section","section_page","row_page","header","counterparty","debtor","cure","agreement","duplicate_row","quote"])("rejects court role escalation or row substitution %s",async k=>{const f=await setup(),c=f.entry.court;if(k==="role")c.role="bankruptcy_debtor";if(k==="current_address")c.currentAddressClaim=true;if(k==="effective_date")c.addressEffectiveDate="2025-07-14";if(k==="contract_date")c.contractDate="2025-07-14";if(k==="bankruptcy")c.counterpartyBankruptcyClaim=true;if(k==="assignment")c.assignmentCompletedClaim=true;if(k==="finance")c.financialInference=true;if(k==="case")c.caseNumber="25-11196-JKS";if(k==="section")c.sectionTitle="Bankrupt Debtors";if(k==="section_page")c.sectionPage=639;if(k==="row_page")c.rowPage=47;if(k==="header")c.header=c.header.replace("Contract Counterparty","Debtor");if(k==="counterparty")c.row.counterparty="Monster Worldwide, LLC";if(k==="debtor")c.row.debtor="RED SKY Consulting LLC";if(k==="cure")c.row.cure="$ 100";if(k==="agreement")c.row.agreement="Loan";if(k==="duplicate_row"){c.pages[8].text+="\r\n"+c.rowQuote;f.rebind();}if(k==="quote")c.rowQuote=c.rowQuote.replace("3015","3016");expect(()=>f.check()).toThrow();});
 it.each(["street","suite","zip","zip5","state","city","email","email_domain","own_email","own_host","own_role","own_phone"])("rejects false address/email bridge %s",async k=>{const f=await setup(),e=f.entry,c=e.court;if(k==="street")c.address.addressLine1="3016 Wyandot St";if(k==="suite")c.address.addressLine2="STE #317";if(k==="zip")c.address.postalCode="80211-9999";if(k==="zip5")e.targetAddress.postalCode="80212";if(k==="state")c.address.state="MN";if(k==="city")c.address.city="Aurora";if(k==="email")c.row.email="stacyw@redsky-consulting.com.evil.test";if(k==="email_domain")e.contactEmailDomain=e.canonicalDomain;if(k==="own_email")e.ownSiteContactEmail="contact@example.com";if(k==="own_host")e.sources[1].url="https://example.com/contact/";if(k==="own_role")e.ownSiteRole="company_legal_registration";if(k==="own_phone")e.phone="7202306991";expect(()=>f.check()).toThrow();});
 it.each(["raw_country","profile_country","presence_flag","jurisdiction","source_same_actor","source_order","original_same_actor","final_same_actor","final_early","final_hash","alias","address","other_case","detail"])("preserves original, source, canonical and final fencing %s",async k=>{const f=await setup(4),e=f.entry,p=f.proof();if(k==="raw_country")e.originalCountry.rawCountry="United States";if(k==="profile_country")e.originalCountry.profileCountryCode="US";if(k==="presence_flag")e.originalCountry.missingValuesPreserved=false;if(k==="jurisdiction")e.originalCountry.jurisdiction="Assumed";if(k==="source_same_actor")e.sourceReviewer.taskId=e.sourceReader.taskId;if(k==="source_order")e.sourceReviewer.reviewedAt="2026-10-01T00:00:00Z";if(k==="original_same_actor")e.originalReviews.independent.taskId=e.originalReviews.primary.taskId;if(k==="final_same_actor")p.reviewer.taskId=p.reader.taskId;if(k==="final_early")p.reader.reviewedAt="2026-10-02T06:00:00Z";if(k==="final_hash")p.reader.evidenceSha256="0".repeat(64);if(k==="alias")f.context.aliases.push("Other LLC");if(k==="address")f.context.addresses.push({...e.targetAddress,sourceKind:"netsuite_record",capturedAt:"2026-10-02T07:00:00Z"});if(k==="other_case")p.entryId=fixture.cases[0].entry.id;if(k==="detail")f.row.detail="Changed";expect(()=>f.check(k.startsWith("final_")||["other_case","detail"].includes(k)?p:undefined)).toThrow();});
});
