import {createHash} from 'node:crypto';
import {describe,it,expect,vi} from 'vitest';
import fixture from '../../test/fixtures/registry-official-api-ra-operator.json';
import {parseRegistryFinding} from './registryProfiles';
const sha=(s:string)=>createHash('sha256').update(s).digest('hex'),now=new Date('2026-10-02T10:00:00Z'),reviewedAt='2026-10-02T09:00:00Z';
async function setup(){
 const f:any=structuredClone(fixture),entry=f.entry,b=entry.siteOperatorBridge;
 vi.resetModules();vi.doMock('./registryOfficialApiEntries.json',()=>({default:{version:1,entries:[entry]}}));
 const api=await import('./registryOfficialApi'),route=await import('./registryOfficialHistory'),row=parseRegistryFinding({...f.finding,registryProfile:f.finding.profile,source:'registry',kind:'ops_profile'},now);
 const proof=()=>{const bare={schema:'official_api_roles_v1' as const,entryId:entry.id,entrySha256:api.registryOfficialApiEntry(entry.id).sha256,canonicalIdentitySha256:entry.canonicalIdentitySha256};const evidenceSha256=api.registryOfficialApiEvidenceHash(row,bare);return {...bare,reader:{taskId:'/test/operator-primary',reviewedAt,evidenceSha256},reviewer:{taskId:'/test/operator-independent',reviewedAt,evidenceSha256}};};
 const check=()=>route.verifyRegistryOfficialHistory(row,proof(),f.company,f.context,now),rebind=()=>entry.canonicalIdentitySha256=api.registryOfficialApiCanonicalHash(f.company,f.context);
 const mutateRaw=(delta:any)=>{entry.source.rawRow=JSON.stringify({...JSON.parse(entry.source.rawRow),...delta});entry.source.rawRowSha256=sha(entry.source.rawRow);entry.source.byteLength=Buffer.byteLength(entry.source.rawRow);};
 return{...f,b,entry,row,api,route,proof,check,rebind,mutateRaw};
}
describe('finite own-site complete operator name bridge',()=>{
 it('retains raw COMPANY, ZIP+4, current short name, no alias/DBA and exact supporting source IDs',async()=>{const f=await setup(),before=JSON.stringify(f.row);expect(f.api.registryOfficialApiCanonicalHash(f.company,f.context)).toBe(f.entry.canonicalIdentitySha256);const v=f.check();expect(JSON.stringify(f.row)).toBe(before);expect(f.context.aliases).toEqual([]);expect(f.row.profile.identity.legalName).toBe('R & A TRUCKING COMPANY');expect(f.row.profile.identity.postalCode).toBe('94621-2539');expect(v.sourceIds).toEqual([`fmcsa:164773:${f.proof().entrySha256}`,'36ffa684-d6fe-4eb8-8fcd-7b52edc9198a']);expect(v.officialHistory).toMatchObject({companyEmailDomain:'ratrucking.com',ownSiteOperatorNameBridge:{legalOperator:'R & A TRUCKING COMPANY',siteLegalOperator:'R&A Trucking Company',canonicalName:'R&A Trucking',canonicalAnchor:{addressLine1:'1050 77th Ave'}}});expect(fixture.preservedUnselected).toHaveLength(26);});
 it('does not normalize COMPANY away or admit without opt-in',async()=>{const f=await setup();delete f.entry.siteOperatorBridge;expect(f.check).toThrow(/operator conflict/);});
 it.each(['wrong_company','wrong_internal','wrong_target','wrong_domain','wrong_mode','extra_key','null','nameBridge','legal_drop_company','site_drop_company','canonical_changed'])('rejects scope or name mutation %s',async k=>{const f=await setup();if(k==='wrong_company')f.entry.companyId='00000000-0000-4000-8000-000000000000';if(k==='wrong_internal')f.entry.internalId='1';if(k==='wrong_target')f.entry.target.recordId='164774';if(k==='wrong_domain')f.entry.canonicalDomain='elsewhere.test';if(k==='wrong_mode')f.entry.anchor={mode:'address_role',role:'carrier_physical',sourceId:f.context.addresses[0].sourceId};if(k==='extra_key')f.b.extra=true;if(k==='null')f.entry.siteOperatorBridge=null;if(k==='nameBridge')f.entry.nameBridge={};if(k==='legal_drop_company')f.b.legalOperator='R & A TRUCKING';if(k==='site_drop_company')f.b.siteLegalOperator='R&A Trucking';if(k==='canonical_changed')f.company.name='Other Trucking';f.rebind();expect(f.check).toThrow();});
 it.each(['missing_address','wrong_street','unit_added','wrong_city','wrong_state','wrong_zip','bad_country','bad_kind','missing_id','missing_date','duplicate','other_alias'])('rejects current canonical change %s even after hash rebind',async k=>{const f=await setup(),a=f.context.addresses[0];if(k==='missing_address')f.context.addresses=[];if(k==='wrong_street')a.addressLine1='1051 77th Ave';if(k==='unit_added')a.addressLine2='Suite 2';if(k==='wrong_city')a.city='Berkeley';if(k==='wrong_state')a.state='CO';if(k==='wrong_zip')a.postalCode='94622';if(k==='bad_country')a.countryCode='CA';if(k==='bad_kind')a.sourceKind='sam_poc';if(k==='missing_id')a.sourceId='';if(k==='missing_date')a.capturedAt='';if(k==='duplicate')f.context.addresses.push({...a});if(k==='other_alias')f.context.aliases.push('Other Company');f.rebind();expect(f.check).toThrow();});
 it.each(['off_domain','lookalike','query','credentials','http_final','status','mime','text_hash','html_hash','receipt_hash','observed','hops_missing','hops_end','hops_status','same_url','wrong_role','missing_page'])('rejects website provenance mutation %s',async k=>{const f=await setup(),p=f.b.pages[0];if(k==='off_domain')p.finalUrl='https://other.test/';if(k==='lookalike')p.finalUrl='https://ratrucking.com.evil.test/';if(k==='query')p.finalUrl+='?x=1';if(k==='credentials')p.finalUrl='https://user@ratrucking.com/';if(k==='http_final')p.finalUrl='http://ratrucking.com/';if(k==='status')p.status=206;if(k==='mime')p.contentType='application/json';if(k==='text_hash')p.textSha256='0'.repeat(64);if(k==='html_hash')p.htmlSha256='';if(k==='receipt_hash')p.receiptSha256='';if(k==='observed')p.observedAt='';if(k==='hops_missing')p.hops=[];if(k==='hops_end')p.hops.at(-1).url='https://ratrucking.com/other/';if(k==='hops_status')p.hops[0].status=200;if(k==='same_url')f.b.pages[1].finalUrl=p.finalUrl;if(k==='wrong_role')p.role='company_headquarters';if(k==='missing_page')f.b.pages.pop();expect(f.check).toThrow();});
 it.each(['operator_absent','operator_duplicate','operator_negated','operator_partner','contact_absent','contact_duplicate','contact_wrong_role','contact_legal_missing','site_unit','site_city','site_zip','phone'])('rejects full text attribution or address mutation %s',async k=>{const f=await setup(),b=f.b,op=b.pages[0],cp=b.pages[1];if(k==='operator_absent')op.text=op.text.replace(b.operatorQuote,'');if(k==='operator_duplicate')op.text+=b.operatorQuote;if(k==='operator_negated'||k==='operator_partner'){const q=b.operatorQuote.replace('is a family',k==='operator_negated'?'is not a family':'is a partner family');op.text=op.text.replace(b.operatorQuote,q);b.operatorQuote=q;}if(k==='contact_absent')cp.text=cp.text.replace(b.contactQuote,'');if(k==='contact_duplicate')cp.text+=b.contactQuote;if(k==='contact_wrong_role'){const q=b.contactQuote.replace('HEADQUARTERS','REGISTERED AGENT');cp.text=cp.text.replace(b.contactQuote,q);b.contactQuote=q;}if(k==='contact_legal_missing'){const q=b.contactQuote.replace('R&A TRUCKING COMPANY','R&A TRUCKING');cp.text=cp.text.replace(b.contactQuote,q);b.contactQuote=q;}if(k==='site_unit')b.address.addressLine2='Suite 1';if(k==='site_city')b.address.city='Berkeley';if(k==='site_zip')b.address.postalCode='94622';if(k==='phone')b.phone='5106327113';op.textSha256=sha(op.text);cp.textSha256=sha(cp.text);expect(f.check).toThrow();});
 it.each([{legal_name:'R & A TRUCKING'},{dba_name:'R&A Trucking'},{phy_street:'1050 77TH AVE STE 1'},{phy_city:'BERKELEY'},{phy_zip:'94622-2539'},{phone:'5106327113'},{email_address:'eric@gmail.com'},{email_address:'eric@sub.ratrucking.com'},{email_address:'eric@ratrucking.com.evil.test'},{dot_number:'164774'}])('rejects altered raw official field %j',async delta=>{const f=await setup();f.mutateRaw(delta);expect(f.check).toThrow();});
 it.each(['same_actor','early','late_reviewer_order','bad_pin','bad_actor'])('rejects operator source lineage mutation %s',async k=>{const f=await setup(),b=f.b;if(k==='same_actor')b.sourceReviewer.taskId=b.sourceReader.taskId;if(k==='early')b.sourceReader.reviewedAt='2026-09-29T00:00:00Z';if(k==='late_reviewer_order')b.sourceReviewer.reviewedAt='2026-10-02T07:59:00Z';if(k==='bad_pin')b.sourceReader.receiptSha256='';if(k==='bad_actor')b.sourceReader.taskId='';expect(f.check).toThrow();});
 it.each(['same_actor','early','changed_detail','changed_original','wrong_hash'])('retains exact final witness fences %s',async k=>{const f=await setup(),p=f.proof();if(k==='same_actor')p.reviewer.taskId=p.reader.taskId;if(k==='early')p.reader.reviewedAt='2026-10-02T08:00:00Z';if(k==='changed_detail')f.row.detail+=' changed';if(k==='changed_original')f.row.evidence+=' changed';if(k==='wrong_hash')p.reader.evidenceSha256='0'.repeat(64);expect(()=>f.route.verifyRegistryOfficialHistory(f.row,p,f.company,f.context,now)).toThrow();});
});
