import { createHash } from "node:crypto";
import { beforeEach, describe, expect, it, vi } from "vitest";
const fetch = vi.hoisted(() => vi.fn());
vi.mock("@/lib/triggers/urlSafety", async original => ({ ...await original<typeof import("@/lib/triggers/urlSafety")>(), fetchPublicHttpText:fetch }));
import { htmlToVisibleText } from "@/lib/sources/siteDiscovery";
import { parseRegistryFinding, registryContentHash, stableRegistryJson, type RegistryFinding } from "./registryProfiles";
import { registryWebsiteEvidenceHash, parseRegistryWebsiteCorroboration, registryWebsiteVerifier, type RegistryWebsiteCorroboration } from "./registryWebsite";
const now = new Date("2026-10-05T02:00:00Z"), sha=(s:string)=>createHash("sha256").update(s).digest("hex");
const company={name:"Example Health",domain:"example.com"},context={aliases:[] as string[],addresses:[],context:""};
const contact="<main>Example Health Contact us Office 123 E Main Street Suite 400 Austin, Texas 78701</main>";
const quote='"Example Health," "we," "our," or "us," means Exact Operator, LLC d/b/a Example Health, a Delaware limited liability company, our employees, officers, directors, parent, affiliates and subsidiaries.';
const policy="<h1>Privacy Policy</h1><p>Effective October 1, 2024.</p><p>"+quote+"</p><p>We use cookies and process data.</p>";
const contactUrl="https://example.com/contact",operatorUrl="https://example.com/privacy";
const identity={legalName:"EXACT OPERATOR LLC",addressLine1:"123 E MAIN ST STE 400",city:"AUSTIN",state:"TX",postalCode:"787011234",countryCode:"US" as const};
function row(){const sourceRow={...identity,npi:"1306616339",organization_type:"2"},evidence=JSON.stringify(sourceRow);return parseRegistryFinding({source:"registry",kind:"ops_profile",internalId:"123",companyId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",sourceUrl:"https://download.cms.gov/nppes/NPPES_Data_Dissemination_September_2026_V2.zip",detail:"Dated organizational registry facts, not current capacity.",evidence,registryProfile:{version:1,dataset:"cms_nppes",recordId:"1306616339",sourceAsOf:"2026-09-13",observedAt:"2026-09-29T00:00:00Z",identity:{...identity},facts:[{field:"npi",value:"1306616339"},{field:"organization_type",value:"2"}],provenance:{rowSha256:sha(evidence),quote:evidence,sourceRow}}},now);}
function unsigned(body=contact,operator=policy):Omit<RegistryWebsiteCorroboration,"reader"|"reviewer">{const text=htmlToVisibleText(body),op=htmlToVisibleText(operator);return{mode:"site_operator_address",sourceUrl:contactUrl,observedAt:"2026-09-30T00:00:00Z",subject:company.name,normalizedVisibleTextSha256:sha(text),quote:text,quoteSha256:sha(text),address:{addressLine1:"123 E Main Street",addressLine2:"Suite 400",city:"Austin",state:"TX",postalCode:"78701",countryCode:"US"},operatorPage:{schema:"explicit_site_operator_dba_definition_v1",sourceUrl:operatorUrl,observedAt:"2026-10-05T01:00:00Z",normalizedVisibleTextSha256:sha(op),quote,quoteSha256:sha(quote),legalOperator:"Exact Operator, LLC"}};}
function signed(r=row(),p=unsigned()):RegistryWebsiteCorroboration{const evidenceSha256=registryWebsiteEvidenceHash(r,p);return{...p,reader:{taskId:"/test/primary",reviewedAt:"2026-10-05T01:30:00Z",evidenceSha256},reviewer:{taskId:"/test/independent",reviewedAt:"2026-10-05T01:40:00Z",evidenceSha256}};}
function setup(body=contact,operator=policy){fetch.mockImplementation(async(url:string)=>({status:200,contentType:"text/html; charset=utf-8",finalUrl:url,body:url===contactUrl?body:operator}));}
beforeEach(()=>{fetch.mockReset();setup();});
async function verify(p=signed(),r=row(),c=company,ctx=context){return registryWebsiteVerifier()(r,p,c,ctx,now);}
describe("separate own-domain operator definition and complete contact address",()=>{
 it("binds both entire pages while preserving registry content and original address roles",async()=>{const r=row(),old=JSON.stringify(r),contentHash=registryContentHash(r.profile,r.sourceUrl,r.detail),v=await verify(signed(r),r);expect(v.method).toBe("official_website_corroboration");expect(v.sourceIds).toEqual(["website:sha256:"+sha(htmlToVisibleText(contact)),"website:sha256:"+sha(htmlToVisibleText(policy))]);expect(v.website?.binding).toBe("exact_own_site_legal_operator_dba_two_page_full_address");expect(v.website?.registryAddress).toEqual(identity);expect(v.website?.websiteDba).toBe(company.name);expect(v.website).not.toHaveProperty("originalDba");expect(v.website?.operatorPageVerification).toMatchObject({finalUrl:operatorUrl,htmlSha256:sha(policy)});expect(JSON.stringify(r)).toBe(old);expect(registryContentHash(r.profile,r.sourceUrl,r.detail)).toBe(contentHash);expect(fetch).toHaveBeenCalledTimes(2);});
 it("also accepts a complete explicit operated-by definition without changing source roles",async()=>{const q='This website is operated by Exact Operator, LLC doing business as Example Health.',op="<p>"+q+"</p>",p=unsigned(contact,op);p.operatorPage!.quote=q;p.operatorPage!.quoteSha256=sha(q);setup(contact,op);expect((await verify(signed(row(),p))).method).toBe("official_website_corroboration");});
 it.each(["Exact Operator Inc","Exact Operator","Other Operator LLC","Global Exact Operator LLC"])("rejects legal-entity mismatch %s",async legal=>{const p=unsigned();p.operatorPage!.legalOperator=legal;await expect(verify(signed(row(),p))).rejects.toThrow();});
 it.each(["Example","Example Health Inc","Example Health West"])("rejects a clipped/different canonical brand %s",async name=>{await expect(verify(signed(),row(),{...company,name})).rejects.toThrow();});
 it("does not borrow a conflicting canonical alias",async()=>{await expect(verify(signed(),row(),company,{...context,aliases:["Other Operator LLC"]})).rejects.toThrow();});
 it.each([{addressLine1:"124 E Main Street"},{addressLine2:"Suite 500"},{addressLine2:undefined},{city:"Dallas"},{state:"CA"},{postalCode:"78702"},{countryCode:"CA" as const}])("preserves all registry address components %j",async change=>{const p=unsigned();p.address={...p.address!,...change};const body="<main>Example Health Office "+[p.address.addressLine1,p.address.addressLine2,p.address.city,p.address.state,p.address.postalCode].filter(Boolean).join(" ")+"</main>";p.quote=htmlToVisibleText(body);p.quoteSha256=sha(p.quote);p.normalizedVisibleTextSha256=sha(p.quote);setup(body);await expect(verify(signed(row(),p))).rejects.toThrow();});
 it.each(["customer's office","affiliate office","former office","registered agent office"])("rejects changed contact role %s",async role=>{const body=contact.replace("Office",role);setup(body);await expect(verify(signed(row(),unsigned(body)))).rejects.toThrow();});
 it.each(["Not ","Example: ","Former ","Our client ","Affiliate "])("rejects misleading operator context %s",async prefix=>{const op=policy.replace("<p>"+quote,"<p>"+prefix+quote);setup(contact,op);await expect(verify(signed(row(),unsigned(contact,op)))).rejects.toThrow();});
 it.each(["not means","formerly means","is affiliated with"])("rejects weakened/negative relationship grammar %s",async word=>{const q=quote.replace("means",word),op=policy.replace(quote,q),p=unsigned(contact,op);p.operatorPage!.quote=q;p.operatorPage!.quoteSha256=sha(q);setup(contact,op);await expect(verify(signed(row(),p))).rejects.toThrow();});
 it("rejects a second operator statement outside the selected exact quote",async()=>{const op=policy+"<p>This website is operated by Other LLC.</p>";setup(contact,op);await expect(verify(signed(row(),unsigned(contact,op)))).rejects.toThrow();});
 it("rejects an explicit later disavowal of the definition",async()=>{const op=policy.replace("</p><p>We use","</p><p>This definition is outdated.</p><p>We use");setup(contact,op);await expect(verify(signed(row(),unsigned(contact,op)))).rejects.toThrow();});
 it("rejects another suffix for the complete operator elsewhere on the page",async()=>{const op=policy+"<p>Exact Operator Inc</p>";setup(contact,op);await expect(verify(signed(row(),unsigned(contact,op)))).rejects.toThrow();});
 it("rejects an appended legal suffix on the contact brand",async()=>{const body=contact.replace("Example Health","Example Health LLC");setup(body);await expect(verify(signed(row(),unsigned(body)))).rejects.toThrow();});
 it("rejects duplicate operator definition",async()=>{const op=policy+"<p>"+quote+"</p>";setup(contact,op);await expect(verify(signed(row(),unsigned(contact,op)))).rejects.toThrow();});
 it.each(["contact","operator"])("rejects changed full-page %s bytes despite unchanged quotation",async role=>{setup(role==="contact"?contact+"<p>changed</p>":contact,role==="operator"?policy+"<p>changed</p>":policy);await expect(verify()).rejects.toThrow("changed");});
 it.each(["contact","operator"])("rejects %s foreign requested source",async role=>{const p=unsigned();if(role==="contact")p.sourceUrl="https://other.com/contact";else p.operatorPage!.sourceUrl="https://other.com/privacy";await expect(verify(signed(row(),p))).rejects.toThrow("own-domain");});
 it.each(["contact","operator"])("rejects %s foreign final source",async role=>{fetch.mockImplementation(async(url:string)=>({status:200,contentType:"text/html",body:url===contactUrl?contact:policy,finalUrl:(role==="contact"?url===contactUrl:url===operatorUrl)?"https://other.com/":url}));await expect(verify()).rejects.toThrow("own-domain");});
 it.each(["contact","operator"])("rejects %s same-host different-path redirect",async role=>{fetch.mockImplementation(async(url:string)=>({status:200,contentType:"text/html",body:url===contactUrl?contact:policy,finalUrl:(role==="contact"?url===contactUrl:url===operatorUrl)?url+"-changed":url}));await expect(verify()).rejects.toThrow("redirected");});
 it.each([false,true])("treats punctuation in the entire canonical brand literally, conflicting suffix=%s",async conflict=>{const subject="Example (Health)",body=contact.replaceAll("Example Health",subject+(conflict?" LLC":"")),op=policy.replaceAll("Example Health",subject),p=unsigned(body,op);p.subject=subject;p.operatorPage!.quote=quote.replaceAll("Example Health",subject);p.operatorPage!.quoteSha256=sha(p.operatorPage!.quote);setup(body,op);const attempt=verify(signed(row(),p),row(),{...company,name:subject});if(conflict)await expect(attempt).rejects.toThrow("conflicting operator");else expect((await attempt).method).toBe("official_website_corroboration");});
 it("requires distinct final page URLs",async()=>{fetch.mockImplementation(async(url:string)=>({status:200,contentType:"text/html",finalUrl:contactUrl,body:url===contactUrl?contact:policy}));await expect(verify()).rejects.toThrow("same page");});
 it.each(["normalization","identifier","canonicalRedirect","operatorRelationship"])("rejects mixed evidence mode %s",field=>{const p=unsigned() as unknown as Record<string,unknown>;p[field]=field==="normalization"?"gravity_forms_honeypot_v1":{};expect(()=>parseRegistryWebsiteCorroboration(signed(row(),p as unknown as ReturnType<typeof unsigned>),row(),now)).toThrow();});
 it("does not allow operator evidence in legacy address mode",()=>{const p=unsigned();delete p.mode;expect(()=>parseRegistryWebsiteCorroboration(signed(row(),p),row(),now)).toThrow();});
 it.each(["contact","operator"])("requires actual %s capture before primary review",role=>{const p=unsigned();if(role==="contact")p.observedAt="2026-10-05T01:31:00Z";else p.operatorPage!.observedAt="2026-10-05T01:31:00Z";expect(()=>parseRegistryWebsiteCorroboration(signed(row(),p),row(),now)).toThrow("precedes");});
 it("requires actual distinct ordered final readers",async()=>{const p=signed();p.reviewer.taskId=p.reader.taskId;await expect(verify(p)).rejects.toThrow("independent");const q=signed();q.reviewer.reviewedAt="2026-10-05T01:29:00Z";await expect(verify(q)).rejects.toThrow("precedes");});
 it.each(["sourceHash","quote","legalOperator","observedAt"])("binds exact second-page %s to both witnesses",field=>{const p=signed();if(field==="sourceHash")p.operatorPage!.normalizedVisibleTextSha256="0".repeat(64);else if(field==="quote")p.operatorPage!.quote+=" changed";else if(field==="legalOperator")p.operatorPage!.legalOperator="Other LLC";else p.operatorPage!.observedAt="2026-10-04T00:00:00Z";expect(()=>parseRegistryWebsiteCorroboration(p,row(),now)).toThrow();});
 it.each(["detail","evidence","recordId","sourceAsOf","observedAt"])("binds exact original publication %s",field=>{const r=row(),p=signed(r);if(field==="detail"||field==="evidence")r[field]+=" changed";else (r.profile as unknown as Record<string,unknown>)[field]="changed";expect(()=>parseRegistryWebsiteCorroboration(p,r,now)).toThrow();});
 it("rejects a nonorganizational NPI or missing explicit country",async()=>{const r=row();r.profile.facts.find(f=>f.field==="organization_type")!.value="1";await expect(verify(signed(r),r)).rejects.toThrow();const x=row();delete x.profile.identity.countryCode;await expect(verify(signed(x),x)).rejects.toThrow();});
 it("keeps request-local page budget at three and reuses each exact source",async()=>{const v=registryWebsiteVerifier(),r=row(),p=signed(r);await v(r,p,company,context,now);await v(r,p,company,context,now);expect(fetch).toHaveBeenCalledTimes(2);const q=unsigned();q.sourceUrl="https://example.com/contact2";q.operatorPage!.sourceUrl="https://example.com/privacy2";fetch.mockImplementation(async(url:string)=>({status:200,contentType:"text/html",finalUrl:url,body:url.includes("contact")?contact:policy}));await expect(v(r,signed(r,q),company,context,now)).rejects.toThrow("three source pages");expect(fetch).toHaveBeenCalledTimes(3);});
 it("keeps omitted-mode legacy hash serialization unchanged",()=>{const r=row(),p=unsigned();delete p.mode;delete p.operatorPage;delete p.observedAt;expect(registryWebsiteEvidenceHash(r,p)).toBe(sha(stableRegistryJson({companyId:r.companyId,internalId:r.internalId,dataset:r.profile.dataset,recordId:r.profile.recordId,rowSha256:r.profile.provenance.rowSha256,...p})));});
});
