import { createHash } from "node:crypto";
import { beforeEach, describe, expect, it, vi } from "vitest";
const fetch = vi.hoisted(() => vi.fn());
vi.mock("@/lib/triggers/urlSafety", async original => ({ ...await original<typeof import("@/lib/triggers/urlSafety")>(), fetchPublicHttpText: fetch }));
import { htmlToVisibleText } from "@/lib/sources/siteDiscovery";
import { parseRegistryFinding, registryContentHash, stableRegistryJson, verifyRegistryIdentity } from "./registryProfiles";
import { registryWebsiteEvidenceHash, parseRegistryWebsiteCorroboration, registryWebsiteVerifier, type RegistryWebsiteCorroboration } from "./registryWebsite";
const now = new Date("2026-10-01T00:00:00Z"), sha = (s:string) => createHash("sha256").update(s).digest("hex");
const marker = "\nOriginal public source row: ";
const raw = {dot_number:"1234567",dba_name:"BRAND CARGO",legal_name:"ORIGINAL OPERATOR LLC",phy_street:"123 N MAIN ST STE 4",phy_city:"AUSTIN",phy_state:"TX",phy_zip:"78701",phy_country:"US"};
const identity = {legalName:raw.legal_name,addressLine1:raw.phy_street,city:raw.phy_city,state:raw.phy_state,postalCode:raw.phy_zip,countryCode:"US" as const};
const company = {name:"Brand Cargo",domain:"brand.com"},context={aliases:[] as string[],addresses:[],context:""};
const html="<footer>Brand Cargo Headquarters 123 N Main St Suite 4 Austin TX 78701</footer>";
function row() { const sourceRow={...identity,usdot_number:raw.dot_number}, original=JSON.stringify(raw),evidence=JSON.stringify(sourceRow)+marker+original;
 return parseRegistryFinding({source:"registry",kind:"ops_profile",companyId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",internalId:"123",sourceUrl:"https://safer.fmcsa.dot.gov/query.asp?query_string=1234567",evidence,detail:"Dated original operator transport facts.",registryProfile:{version:1,dataset:"fmcsa",recordId:raw.dot_number,sourceAsOf:"2026-09-29",observedAt:now.toISOString(),identity:{...identity},facts:[{field:"usdot_number",value:raw.dot_number}],provenance:{sourceRow,quote:evidence,rowSha256:sha(original)}}},now); }
function proof(r=row(),body=html,override:Partial<Omit<RegistryWebsiteCorroboration,"reader"|"reviewer">>={}) { const text=htmlToVisibleText(body); const base:Omit<RegistryWebsiteCorroboration,"reader"|"reviewer">={mode:"registry_dba_address",sourceUrl:"https://brand.com/",subject:"Brand Cargo",quote:text,quoteSha256:sha(text),normalizedVisibleTextSha256:sha(text),address:{addressLine1:"123 N Main St",addressLine2:"Suite 4",city:"Austin",state:"TX",postalCode:"78701",countryCode:"US"},...override};const evidenceSha256=registryWebsiteEvidenceHash(r,base);return {...base,reader:{taskId:"/test/reader",reviewedAt:now.toISOString(),evidenceSha256},reviewer:{taskId:"/test/reviewer",reviewedAt:now.toISOString(),evidenceSha256}}; }
function page(body=html,finalUrl="https://brand.com/"){return{body,finalUrl,status:200,contentType:"text/html"};}
beforeEach(()=>{fetch.mockReset();fetch.mockResolvedValue(page());});
describe("original FMCSA DBA plus complete own-site address",()=>{
 it("preserves operator, source, address context and content while recording the exact DBA binding",async()=>{const r=row(),before=JSON.stringify([r,context]),hash=registryContentHash(r.profile,r.sourceUrl,r.detail);const v=await registryWebsiteVerifier()(r,proof(r),company,context,now);expect(v.website?.binding).toBe("exact_original_registry_dba_full_address");expect(v.website?.originalDba).toBe(raw.dba_name);expect(v.website?.registryAddress).toEqual(identity);expect(JSON.stringify([r,context])).toBe(before);expect(registryContentHash(r.profile,r.sourceUrl,r.detail)).toBe(hash);});
 it("retains numeric address tokens immediately after the complete DBA",async()=>{const r=row(),body=html.replace(" Headquarters","");fetch.mockResolvedValue(page(body));expect((await registryWebsiteVerifier()(r,proof(r,body),company,context,now)).website?.binding).toBe("exact_original_registry_dba_full_address");});
 it("allows the original operator as canonical subject with whole DBA still visible",async()=>{const r=row();expect((await registryWebsiteVerifier()(r,proof(r),{...company,name:"Original Operator"},context,now)).website?.binding).toBe("exact_original_registry_dba_full_address");});
 it.each(["Brand","Brand Cargo West","Brand Cargo LLC","Original Operator Inc","Original Co"])("rejects incompatible canonical names %s",async name=>{const r=row();await expect(registryWebsiteVerifier()(r,proof(r),{...company,name},context,now)).rejects.toThrow("whole canonical");});
 it.each(["OTHER LLC","BRAND CARGO LLC","ORIGINAL OPERATOR INC"])("rejects conflicting aliases %s",async alias=>{const r=row();await expect(registryWebsiteVerifier()(r,proof(r),company,{...context,aliases:[alias]},now)).rejects.toThrow();});
 it.each(["Brand","Brand Cargo Co","Brand Cargo West"])("requires whole original DBA as selected subject %s",async subject=>{const r=row();await expect(registryWebsiteVerifier()(r,proof(r,html,{subject}),company,context,now)).rejects.toThrow();});
 it.each(["dba_name","legal_name","dot_number","phy_street","phy_city","phy_state","phy_zip","phy_country"])("rejects original-row mismatch %s",async field=>{const r=row(),changed=JSON.stringify({...raw,[field]:"OTHER"});r.profile.provenance.quote=r.profile.provenance.quote.split(marker)[0]+marker+changed;r.profile.provenance.rowSha256=sha(changed);await expect(registryWebsiteVerifier()(r,proof(r),company,context,now)).rejects.toThrow();});
 it("rejects unchanged row hash after original byte mutation",async()=>{const r=row();r.profile.provenance.quote += " ";await expect(registryWebsiteVerifier()(r,proof(r),company,context,now)).rejects.toThrow();});
 it.each([{addressLine1:"123 Main St"},{addressLine1:"124 N Main St"},{addressLine2:undefined},{addressLine2:"Suite 5"},{city:"Dallas"},{state:"UT"},{postalCode:"78702"},{countryCode:"CA" as const}])("retains all address components %j",async change=>{const r=row(),a={...proof(r).address!,...change};const body="<footer>Brand Cargo Headquarters "+[a.addressLine1,a.addressLine2,a.city,a.state,a.postalCode].filter(Boolean).join(" ")+"</footer>";fetch.mockResolvedValue(page(body));await expect(registryWebsiteVerifier()(r,proof(r,body,{address:a}),company,context,now)).rejects.toThrow();});
 it.each(["Not Brand Cargo","Global Brand Cargo","Brand Cargo West","Brand Cargo LLC","Customer Brand Cargo","Affiliate Brand Cargo","Brand Cargo operated by Other Inc","Brand Cargo, LLC","Brand Cargo, Inc.","Brand Cargo. Operated by Other LLC","Brand Cargo — Operated by Other LLC","Brand Cargo; owned by Other LLC","Brand Cargo: LLP","Brand Cargo (LLC)","Brand Cargo [Inc.]","Brand Cargo “LLC”","Brand Cargo (Operated by Other LLC)","Brand Cargo (West)","Brand Cargo [Logistics]"])("rejects partial or ambiguous full-page attribution %s",async phrase=>{const r=row(),body="<footer>"+phrase+" Headquarters 123 N Main St Suite 4 Austin TX 78701</footer>";fetch.mockResolvedValue(page(body));await expect(registryWebsiteVerifier()(r,proof(r,body),company,context,now)).rejects.toThrow();});
 it("does not hide a conflicting full-page mention by clipping the quote",async()=>{const r=row(),body=html+"<p>Customer Brand Cargo LLC</p>";fetch.mockResolvedValue(page(body));await expect(registryWebsiteVerifier()(r,proof(r,body,{quote:htmlToVisibleText(html),quoteSha256:sha(htmlToVisibleText(html))}),company,context,now)).rejects.toThrow();});
 it("allows only the exact neutral Skip to content heading without removing evidence",async()=>{const r=row(),body="<p>Skip to content Brand Cargo Menu.</p>"+html;fetch.mockResolvedValue(page(body));expect((await registryWebsiteVerifier()(r,proof(r,body,{quote:htmlToVisibleText(html),quoteSha256:sha(htmlToVisibleText(html))}),company,context,now)).method).toBe("official_website_corroboration");});
 it.each(["detail","evidence","observedAt"])("binds exact parsed publication content %s",field=>{const r=row(),p=proof(r);if(field==="observedAt")r.profile.observedAt="2026-09-30T00:00:00Z";else r[field as "detail"|"evidence"]="changed";expect(()=>parseRegistryWebsiteCorroboration(p,r,now)).toThrow();});
 it("rejects another labelled USDOT on the full page",async()=>{const r=row(),body=html+"<p>USDOT 7654321</p>";fetch.mockResolvedValue(page(body));await expect(registryWebsiteVerifier()(r,proof(r,body,{quote:htmlToVisibleText(html),quoteSha256:sha(htmlToVisibleText(html))}),company,context,now)).rejects.toThrow("conflicting labelled USDOT");});
 it("requires fresh distinct independent attestations",async()=>{const r=row(),p=proof(r);p.reviewer.taskId=p.reader.taskId;await expect(registryWebsiteVerifier()(r,p,company,context,now)).rejects.toThrow("independent");const old=proof(r);old.reader.reviewedAt="2020-01-01T00:00:00Z";await expect(registryWebsiteVerifier()(r,old,company,context,now)).rejects.toThrow();});
 it("requires fresh full HTML hash and same own-domain",async()=>{const r=row(),p=proof(r);fetch.mockResolvedValueOnce(page(html+" changed"));await expect(registryWebsiteVerifier()(r,p,company,context,now)).rejects.toThrow("changed");fetch.mockResolvedValueOnce(page(html,"https://other.com/"));await expect(registryWebsiteVerifier()(r,p,company,context,now)).rejects.toThrow("own-domain");});
 it("rejects arbitrary modes, foreign identifiers, missing source country and another dataset",async()=>{const r=row();expect(()=>parseRegistryWebsiteCorroboration({...proof(r),mode:"fuzzy"},r,now)).toThrow();expect(()=>parseRegistryWebsiteCorroboration({...proof(r),identifier:{kind:"usdot",value:raw.dot_number}},r,now)).toThrow();delete r.profile.identity.countryCode;await expect(registryWebsiteVerifier()(r,proof(r),company,context,now)).rejects.toThrow();const other=row();other.profile.dataset="co_sos";await expect(registryWebsiteVerifier()(other,proof(other),company,context,now)).rejects.toThrow();});
 it("keeps omitted-mode and identifier-mode hash serialization byte-compatible",()=>{const r=row();for(const mode of [undefined,"registry_identifier"] as const){const {reader,reviewer,...p}=proof(r);const base={...p,mode,...(mode?{identifier:{kind:"usdot" as const,value:raw.dot_number}}:{})};const legacy={companyId:r.companyId,internalId:r.internalId,dataset:r.profile.dataset,recordId:r.profile.recordId,rowSha256:r.profile.provenance.rowSha256,...base};const exact=mode?{...legacy,identifierContent:{contentHash:registryContentHash(r.profile,r.sourceUrl,r.detail),evidenceSha256:sha(r.evidence),observedAt:r.profile.observedAt}}:legacy;expect(registryWebsiteEvidenceHash(r,base)).toBe(sha(stableRegistryJson(exact)));}});
 it("keeps canonical DBA admission unchanged, without borrowing website proof into context",()=>{const r=row();expect(verifyRegistryIdentity(r.profile,company,context,[],now)).toBeNull();const address={...identity,sourceId:"record-1",sourceKind:"netsuite_record" as const,capturedAt:now.toISOString()};expect(verifyRegistryIdentity(r.profile,company,{...context,addresses:[address]},[],now)?.method).toBe("exact_registry_dba_address");});
});
