import { createHash } from "node:crypto";
import { describe,expect,it,vi } from "vitest";
import fixture from "../../test/fixtures/registry-official-enercom-documents.json";
import catalog from "./registryOfficialDocumentEntries.json";
import { parseRegistryFinding,stableRegistryJson } from "./registryProfiles";
import type { CompanyIdentityContext } from "@/lib/companyIdentity";
const sha=(s:string)=>createHash("sha256").update(s).digest("hex"),now=new Date("2026-10-02T07:00:00Z"),at="2026-10-02T06:45:00Z";
async function setup(index=0){
 const cases=structuredClone(fixture.cases),f=cases[index],entry=f.entry,entries=[...structuredClone(catalog.entries.slice(0,4)),...cases.map(x=>x.entry)];
 vi.resetModules();vi.doMock("./registryOfficialDocumentEntries.json",()=>({default:{schema:"reviewed_official_document_entries_v1",entries}}));
 const module=await import("./registryOfficialDocuments"),route=await import("./registryOfficialHistory"),row=parseRegistryFinding(f.finding,now);
 const proof=()=>{const bare={schema:"official_document_roles_v1" as const,entryId:entry.id,entrySha256:module.registryOfficialDocumentEntry(entry.id).sha256,canonicalIdentitySha256:entry.canonicalIdentitySha256},evidenceSha256=module.registryOfficialDocumentEvidenceHash(row,bare);return {...bare,reader:{taskId:"/test/enercom-primary",reviewedAt:at,evidenceSha256},reviewer:{taskId:"/test/enercom-independent",reviewedAt:at,evidenceSha256}};};
 const rebindText=()=>{entry.sources[0].text=entry.pdf.pages.map(p=>`--- PAGE ${p.page} ---\n${p.text}`).join("\n\n");entry.sources[0].textSha256=sha(entry.sources[0].text);for(const p of entry.pdf.pages)p.textSha256=sha(p.text);};
 return {...f,cases,entry,entries,row,module,proof,rebindText,check:(p=proof())=>route.verifyRegistryOfficialHistory(row,p,f.company,f.context as CompanyIdentityContext,now)};
}
describe("reviewed company-hosted PDF historical contact role",()=>{
 it.each([0,1])("accepts exact separate UCC case %i using only synthetic final witnesses",async index=>{const f=await setup(index),before=JSON.stringify(f.row),r=f.check();expect(r.method).toBe("reviewed_official_registration_history");expect(r.officialHistory?.targetAddress).toMatchObject({role:"debtor_business",addressLine1:"410 17th Street, Suite 250"});expect(r.officialHistory?.canonicalAddresses).toEqual(f.context.addresses);expect(f.context.addresses[0].addressLine1).toBe("633 17th St Ste 1645");expect(JSON.stringify(f.row)).toBe(before);expect(f.entry.sources[0].sourceDate).toBeNull();expect(f.entry.pdf.period.year).toBe("2020");expect(f.entry.pdf.pages).toHaveLength(7);});
 it("preserves all four prior entries and keeps the two same-day originals distinct",async()=>{const f=await setup();for(const e of catalog.entries.slice(0,4))expect(f.module.registryOfficialDocumentEntry(e.id).sha256).toBe(sha(stableRegistryJson(e)));expect(f.entries).toHaveLength(6);expect(f.cases[0].entry.target.recordId).not.toBe(f.cases[1].entry.target.recordId);expect(f.cases[0].entry.target.evidenceSha256).not.toBe(f.cases[1].entry.target.evidenceSha256);});
 it.each(["kind","host","domain_suffix","query","credentials","http","content_type","body","request","hops","final_status","source_date","source_date_text","text_hash","capture_pin"])("rejects altered PDF capture %s",async k=>{const f=await setup(),s=f.entry.sources[0];if(k==="kind")s.kind="municipal_pdf";if(k==="host")s.url=s.url.replace("www.enercominc.com","example.test");if(k==="domain_suffix")s.url=s.url.replace("www.enercominc.com","www.enercominc.com.evil.test");if(k==="query")s.url+="?source=other";if(k==="credentials")s.url=s.url.replace("https://","https://other@");if(k==="http")Object.assign(s,{status:null});if(k==="content_type")s.contentType="text/html";if(k==="body")s.bodySha256="invalid";if(k==="request")s.requestedUrl="https://example.test/document.pdf";if(k==="hops")s.hops=[];if(k==="final_status")s.hops[0].status=404;if(k==="source_date")Object.assign(s,{sourceDate:"2019-12-06"});if(k==="source_date_text")Object.assign(s,{sourceDateText:"2019-12-06"});if(k==="text_hash")s.textSha256="0".repeat(64);if(k==="capture_pin")s.receiptSha256="";expect(()=>f.check()).toThrow();});
 it.each(["count","missing_page","duplicate_page","reordered_page","page_hash","page_visual","extraction_pin","omitted_text","changed_text","identity_page","duplicate_contact"])("requires complete exact PDF page coverage %s",async k=>{const f=await setup(),p=f.entry.pdf;if(k==="count")p.pageCount=6;if(k==="missing_page")p.pages.pop();if(k==="duplicate_page")p.pages[6].page=1;if(k==="reordered_page")p.pages.reverse();if(k==="page_hash")p.pages[6].textSha256="0".repeat(64);if(k==="page_visual")p.pages[6].visualSha256="";if(k==="extraction_pin")p.extractionReceiptSha256="0".repeat(64);if(k==="omitted_text"){f.entry.sources[0].text=p.pages[0].text;f.entry.sources[0].textSha256=sha(f.entry.sources[0].text);}if(k==="changed_text"){p.pages[6].text+="changed";p.pages[6].textSha256=sha(p.pages[6].text);}if(k==="identity_page")p.identityPage=2;if(k==="duplicate_contact"){p.pages[0].text+=p.contactBlock;f.rebindText();}expect(()=>f.check()).toThrow();});
 it.each(["role","current_address","publication_claim","site_role","legal_name","own_quote","pdf_domain","phone","missing_unit","wrong_unit","city","zip","target_unit","event_year","event_role","event_quote","event_page"])("rejects role, address or date escalation %s",async k=>{const f=await setup(),e=f.entry,p=e.pdf;if(k==="role")p.role="event_venue";if(k==="current_address")p.currentAddressClaim=true;if(k==="publication_claim")p.publicationDateClaim=true;if(k==="site_role")e.ownSiteRole="client_name";if(k==="legal_name")e.ownSiteLegalName="EnerCom LLC";if(k==="own_quote")e.ownSiteIdentityQuote="EnerCom, Inc.";if(k==="pdf_domain")p.domainLiteral="ENERCOMINC.COM.evil.test";if(k==="phone")e.phone="3032968835";if(k==="missing_unit")p.address.addressLine1="410 17TH ST.";if(k==="wrong_unit")p.address.addressLine1="410 17TH ST. SUITE 251";if(k==="city")p.address.city="Boulder";if(k==="zip")p.address.postalCode="80206";if(k==="target_unit")e.targetAddress.addressLine1="410 17th Street, Suite 251";if(k==="event_year")p.period.year="2019";if(k==="event_role")p.period.role="publication_year";if(k==="event_quote")p.period.eventDateQuotes=["February 11-12, 2020"];if(k==="event_page")p.period.eventPage=1;expect(()=>f.check()).toThrow();});
 it.each(["wrong_host","wrong_hops","missing_hops","wrong_status","missing_phone"])("retains own-site authority and phone chain %s",async k=>{const f=await setup(),s=f.entry.sources[1];if(k==="wrong_host")s.url="https://example.test/";if(k==="wrong_hops")s.hops[0].url="http://example.test/";if(k==="missing_hops")s.hops=[];if(k==="wrong_status")s.hops[1].status=403;if(k==="missing_phone"){s.text=s.text.replaceAll("296.8834","296.8835");s.textSha256=sha(s.text);}expect(()=>f.check()).toThrow();});
 it.each(["source_same_actor","source_order","original_same_actor","original_order","final_same_actor","final_early","final_hash","canonical_address","canonical_alias","other_case","detail_replay","raw_row"])("retains source, original, canonical and final fencing %s",async k=>{const f=await setup(),e=f.entry,p=f.proof();if(k==="source_same_actor")e.sourceReviewer.taskId=e.sourceReader.taskId;if(k==="source_order")e.sourceReviewer.reviewedAt="2026-10-02T06:00:00Z";if(k==="original_same_actor")e.originalReviews.independent.taskId=e.originalReviews.primary.taskId;if(k==="original_order")e.originalReviews.independent.reviewedAt="2026-09-29T00:00:00Z";if(k==="final_same_actor")p.reviewer.taskId=p.reader.taskId;if(k==="final_early")p.reviewer.reviewedAt="2026-10-02T06:20:00Z";if(k==="final_hash")p.reader.evidenceSha256="0".repeat(64);if(k==="canonical_address")f.context.addresses[0].addressLine1=e.targetAddress.addressLine1;if(k==="canonical_alias")Object.assign(f.context,{aliases:["Enercom LLC"]});if(k==="other_case")p.entryId=f.cases[1].entry.id;if(k==="detail_replay")f.row.detail="changed";if(k==="raw_row")f.row.evidence+="\n{}";expect(()=>f.check(k.startsWith("final_")||["other_case","detail_replay"].includes(k)?p:undefined)).toThrow();});
 it("has no catalog admission for either unresolved sibling",async()=>{const f=await setup();for(const key of fixture.heldOriginalProfileKeys)expect(()=>f.module.registryOfficialDocumentEntry(key)).toThrow();expect(fixture.heldOriginalProfileKeys).toEqual(["registry:co_sos:19961165129","registry:co_ucc:1399738:1123581"]);});
});
