import { createHash } from "node:crypto";
import { describe,expect,it,vi } from "vitest";
import fixture from "../../test/fixtures/registry-official-siggins-document.json";
import catalog from "./registryOfficialDocumentEntries.json";
import { parseRegistryFinding,stableRegistryJson } from "./registryProfiles";
import type { CompanyIdentityContext } from "@/lib/companyIdentity";
const sha=(s:string)=>createHash("sha256").update(s).digest("hex"),now=new Date("2026-10-02T06:00:00Z"),at="2026-10-02T05:55:00Z";
async function setup(){
 const f=structuredClone(fixture),entry=f.entry,entries=[...structuredClone(catalog.entries.slice(0,3)),entry];
 vi.resetModules();vi.doMock("./registryOfficialDocumentEntries.json",()=>({default:{schema:"reviewed_official_document_entries_v1",entries}}));
 const module=await import("./registryOfficialDocuments"),route=await import("./registryOfficialHistory"),row=parseRegistryFinding(f.finding,now);
 const proof=()=>{const bare={schema:"official_document_roles_v1" as const,entryId:entry.id,entrySha256:module.registryOfficialDocumentEntry(entry.id).sha256,canonicalIdentitySha256:entry.canonicalIdentitySha256},evidenceSha256=module.registryOfficialDocumentEvidenceHash(row,bare);return {...bare,reader:{taskId:"/test/siggins-primary",reviewedAt:at,evidenceSha256},reviewer:{taskId:"/test/siggins-independent",reviewedAt:at,evidenceSha256}};};
 return {...f,entry,entries,row,module,proof,check:(p=proof())=>route.verifyRegistryOfficialHistory(row,p,f.company,f.context as CompanyIdentityContext,now)};
}
describe("finite municipal DBA and typed original CSLB identity",()=>{
 it("accepts exact reviewed source roles with synthetic final witnesses and leaves canonical arrays empty",async()=>{const f=await setup(),before=JSON.stringify(f.row),r=f.check();expect(r.method).toBe("reviewed_official_registration_history");expect(r.officialHistory?.targetAddress).toMatchObject({role:"contractor_mailing_address",legalName:"SIGGINS CO"});expect(r.officialHistory?.canonicalAddresses).toEqual([]);expect(JSON.stringify(f.row)).toBe(before);expect(f.entry.sourceStatus).toBe("QUAL Bond SUSP");expect(f.entry.municipal.currentLicenseClaim).toBe(false);expect(f.entry.sources[0].status).toBeNull();});
 it("preserves all three prior catalog entries exactly",async()=>{const f=await setup();for(const e of catalog.entries.slice(0,3))expect(f.module.registryOfficialDocumentEntry(e.id).sha256).toBe(sha(stableRegistryJson(e)));expect(f.entries).toHaveLength(4);});
 it.each(["http","body","content_type","requested","hops","host","record_url","kind","date"])("rejects invented or wrong municipal capture %s",async k=>{const f=await setup(),s=f.entry.sources[0];if(k==="http")s.status=200;if(k==="body")s.bodySha256="a".repeat(64);if(k==="content_type")s.contentType="text/html";if(k==="requested")s.requestedUrl=s.url;if(k==="hops")s.hops=[{url:s.url,status:200}];if(k==="host")s.url=s.url.replace("blaine.ims16.com","evil.test");if(k==="record_url")s.url=s.url.replace("713445394","713445395");if(k==="kind")s.kind="municipal_pdf";if(k==="date")Object.assign(s,{sourceDate:"2021-03-31",sourceDateText:"03/31/2021"});expect(()=>f.check()).toThrow();});
 it.each(["header_name","header_hash","missing_header_receipt","second_name","second_column","type_column","type_value","raw_extra_name"])("rejects untyped or substituted CSLB name %s",async k=>{const f=await setup(),e=f.entry;if(k==="header_name"){e.csvHeader.text=e.csvHeader.text.replace("BUS-NAME-2","ArbitraryAlias");e.csvHeader.sha256=sha(e.csvHeader.text);}if(k==="header_hash")e.csvHeader.sha256="0".repeat(64);if(k==="missing_header_receipt")e.csvHeader.inspectionReceiptSha256="";if(k==="second_name")e.secondName.value="OTHER EQUIPMENT INC";if(k==="second_column")e.secondName.column="FullBusinessName";if(k==="type_column")e.secondName.typeColumn="BusinessType";if(k==="type_value")e.secondName.typeValue="DBA";
  if(k==="raw_extra_name"){f.row.evidence=f.row.evidence.replace("SIGGINS CO,HIGMAN EQUIPMENT COMPANY INC,,","SIGGINS CO,,HIGMAN EQUIPMENT COMPANY INC,");f.row.profile.provenance.quote=f.row.evidence;f.row.profile.provenance.rowSha256=sha(f.row.evidence);e.target.rowSha256=sha(f.row.evidence);e.target.evidenceSha256=sha(f.row.evidence);e.target.profileSha256=sha(stableRegistryJson(f.row.profile));}expect(()=>f.check()).toThrow();});
 it.each(["legal_role","dba_role","legal_name","dba","email","municipal_unit","target_unit","own_block","duplicate_block","current_license","header_expiry","detail_expiry","source_status"])("rejects changed role or identity %s even with rebound text %s",async k=>{const f=await setup(),e=f.entry,m=e.municipal;
  if(k==="legal_role")m.role="unlabelled_mention";if(k==="dba_role")e.ownSiteRole="regulator_address";if(k==="legal_name")m.legalCompanyName="Other Equipment, Inc / Siggins Company";if(k==="dba")m.dba="Siggins";if(k==="email"){m.companyEmail="lbrown@siggins.com.evil.test";e.sources[0].text=e.sources[0].text.replace("lbrown@siggins.com",m.companyEmail);m.identityQuote=m.identityQuote.replace("lbrown@siggins.com",m.companyEmail);e.sources[0].textSha256=sha(e.sources[0].text);}if(k==="municipal_unit")m.address.addressLine1+=" Suite2";if(k==="target_unit")e.targetAddress.addressLine1+=" Suite2";if(k==="own_block")e.ownSiteContactQuote=e.ownSiteContactQuote.replace("Headquarters","Regulator");if(k==="duplicate_block"){e.sources[0].text+="\n"+m.identityQuote;e.sources[0].textSha256=sha(e.sources[0].text);}if(k==="current_license")m.currentLicenseClaim=true;if(k==="header_expiry")m.headerExpiry="03/31/2027";if(k==="detail_expiry")m.detailExpiry="2027-10-01";if(k==="source_status")e.sourceStatus="Active";expect(()=>f.check()).toThrow();});
 it.each(["source_actor","source_time","original_actor","final_actor","final_hash","canonical_name","canonical_address","detail_replay"])("retains existing lineage/canonical/final gates %s",async k=>{const f=await setup(),e=f.entry,p=f.proof();if(k==="source_actor")e.sourceReviewer.taskId=e.sourceReader.taskId;if(k==="source_time")e.sourceReviewer.reviewedAt="2026-10-02T05:00:00Z";if(k==="original_actor")e.originalReviews.independent.taskId=e.originalReviews.primary.taskId;if(k==="final_actor")p.reviewer.taskId=p.reader.taskId;if(k==="final_hash")p.reader.evidenceSha256="0".repeat(64);if(k==="canonical_name")f.company.name="Siggins";if(k==="canonical_address")Object.assign(f.context,{addresses:[{...e.targetAddress,sourceKind:"netsuite_record",sourceId:"invented",capturedAt:at}]});if(k==="detail_replay")f.row.detail="changed";expect(()=>f.check(["final_actor","final_hash","detail_replay"].includes(k)?p:undefined)).toThrow();});
});
