import {createHash} from "node:crypto";
import {describe,expect,it,vi} from "vitest";
import fixture from "../../test/fixtures/registry-official-dorm-broker.json";
import catalog from "./registryOfficialDocumentEntries.json";
import {parseRegistryFinding,stableRegistryJson} from "./registryProfiles";
import type {CompanyIdentityContext} from "@/lib/companyIdentity";
const sha=(s:string)=>createHash("sha256").update(s).digest("hex"),now=new Date("2026-10-02T12:00:00Z"),at="2026-10-02T11:30:00Z";
async function setup(){
 const f=structuredClone(fixture),entry=f.entry,entries=[...structuredClone(catalog.entries.filter(x=>x.id!==entry.id)),entry];
 vi.resetModules();vi.doMock("./registryOfficialDocumentEntries.json",()=>({default:{schema:"reviewed_official_document_entries_v1",entries}}));
 const module=await import("./registryOfficialDocuments"),route=await import("./registryOfficialHistory"),row=parseRegistryFinding(f.finding,now);
 const proof=()=>{const bare={schema:"official_document_roles_v1" as const,entryId:entry.id,entrySha256:module.registryOfficialDocumentEntry(entry.id).sha256,canonicalIdentitySha256:entry.canonicalIdentitySha256},evidenceSha256=module.registryOfficialDocumentEvidenceHash(row,bare);return {...bare,reader:{taskId:"/test/dorm-primary",reviewedAt:at,evidenceSha256},reviewer:{taskId:"/test/dorm-independent",reviewedAt:at,evidenceSha256}};};
 return {...f,entry,entries,row,module,proof,check:(p=proof())=>route.verifyRegistryOfficialHistory(row,p,f.company,f.context as CompanyIdentityContext,now)};
}
describe("finite own-domain legal terms and exact broker identifiers",()=>{
 it("accepts identity only with synthetic final witnesses and leaves registry/CRM roles unchanged",async()=>{const f=await setup(),before=JSON.stringify(f.row),r=f.check();expect(r.method).toBe("reviewed_official_registration_history");expect(r.officialHistory?.scope).toContain("No website street-address corroboration or current authority");expect(r.officialHistory?.targetAddress).toMatchObject({role:"registered_carrier_broker",addressLine1:"5111 N. SCOTTSDALE RD STE 200"});expect(r.officialHistory?.canonicalAddresses).toEqual(f.context.addresses);expect(f.context.addresses[0].addressLine1).toBe("5111 N Scottsdale Suite 200");expect(JSON.stringify(f.row)).toBe(before);expect(f.entry.broker.websiteStreetAddress).toBeNull();expect(f.row.profile.sourceAsOf).toBeNull();});
 it("preserves all thirteen existing compiled entries and has no SBA sibling admission",async()=>{const f=await setup();expect(f.entries).toHaveLength(14);for(const e of catalog.entries.filter(x=>x.id!==f.entry.id))expect(f.module.registryOfficialDocumentEntry(e.id).sha256).toBe(sha(stableRegistryJson(e)));expect(f.heldProfileKeys).toHaveLength(2);for(const key of f.heldProfileKeys)expect(()=>f.module.registryOfficialDocumentEntry(key)).toThrow();});
 it.each(["id","company","domain","dataset","record","role","extra_source"])("rejects expanded finite scope %s",async k=>{const f=await setup(),e=f.entry;if(k==="id")e.internalId="18302044";if(k==="company")e.companyId="9349a8d8-6261-4f3a-8697-b49e8204448f";if(k==="domain")e.canonicalDomain="dormroommovers.com.evil.test";if(k==="dataset")e.target.dataset="sba_7a";if(k==="record")e.target.recordId="2288434";if(k==="role")e.target.role="borrower_business";if(k==="extra_source")e.sources.push(structuredClone(e.sources[0]));expect(()=>f.check()).toThrow();});
 it.each(["host","http","query","credentials","request","hops","redirect","status","content_type","observed","body","receipt","source_pin","date","date_text","read","truncated","modified_rehashed"])("requires exact complete retained source and provenance %s",async k=>{const f=await setup(),s=f.entry.sources[0];if(k==="host")s.url="https://dormroommovers.com.evil.test/terms";if(k==="http")s.url=s.url.replace("https:","http:");if(k==="query")s.url+="?other=true";if(k==="credentials")s.url=s.url.replace("https://","https://user@");if(k==="request")s.requestedUrl="https://www.dormroommovers.com/privacy";if(k==="hops")s.hops=[];if(k==="redirect")s.hops.push({url:s.url,status:200});if(k==="status")s.status=403;if(k==="content_type")s.contentType="application/pdf";if(k==="observed")s.observedAt="2026-10-02T08:05:00Z";if(k==="body")s.bodySha256="0".repeat(64);if(k==="receipt")s.receiptSha256="0".repeat(64);if(k==="source_pin")s.originalSourcePin="0".repeat(64);if(k==="date")Object.assign(s,{sourceDate:"2026-10-02"});if(k==="date_text")Object.assign(s,{sourceDateText:"Copyright 2007-2026"});if(k==="read")s.completeRead=false;if(k==="truncated")s.text=s.text.slice(0,1000);if(k==="modified_rehashed"){s.text=s.text.replace("2288433","2288434");s.textSha256=sha(s.text);}expect(()=>f.check()).toThrow();});
 it.each(["role","legal","dot","mc","contract","disclosure","registry_role","website_address","address_corroborated","authority","full_read","rendered","effective_date"])("rejects invented identity, role or qualification %s",async k=>{const f=await setup(),b=f.entry.broker;if(k==="role")b.ownSiteRole="customer_mention";if(k==="legal")b.termsLegalName="Dorm Room Movers Inc";if(k==="dot")b.usdot="2288434";if(k==="mc")b.mc="746976";if(k==="contract")b.contractQuote="Dorm Room Movers, LLC";if(k==="disclosure")b.disclosureQuote="USDOT 2288433";if(k==="registry_role")b.registrationAddressRole="website_address";if(k==="website_address")Object.assign(b,{websiteStreetAddress:"5111 N Scottsdale Rd Ste 200"});if(k==="address_corroborated")b.physicalAddressCorroborated=true;if(k==="authority")b.currentAuthorityClaim=true;if(k==="full_read")b.fullNormalizedTextRead=false;if(k==="rendered")b.renderedCompletenessClaim=true;if(k==="effective_date")Object.assign(b,{termsEffectiveDate:"2026-10-02"});expect(()=>f.check()).toThrow();});
 it.each(["raw_mc","raw_dot","raw_legal","country","fact","units","date","profile_pin","source_url","address"])("preserves all original profile bytes and fields %s",async k=>{const f=await setup();if(k==="raw_mc")f.row.evidence=f.row.evidence.replace('"746975"','"746976"');if(k==="raw_dot")f.row.evidence=f.row.evidence.replaceAll('"2288433"','"2288434"');if(k==="raw_legal")f.row.profile.identity.legalName="DORM ROOM MOVERS INC";if(k==="country")delete f.row.profile.identity.countryCode;if(k==="fact")f.row.profile.facts[0].value="2288434";if(k==="units")f.row.profile.facts.find(x=>x.field==="power_units")!.value=10;if(k==="date")f.row.profile.sourceAsOf="2026-10-02";if(k==="profile_pin")f.entry.target.profileSha256="0".repeat(64);if(k==="source_url")f.row.sourceUrl=f.row.sourceUrl.replace("2288433","2288434");if(k==="address")f.row.profile.identity.addressLine1="5111 N SCOTTSDALE RD";expect(()=>f.check()).toThrow();});
 it.each(["source_same","source_before_capture","original_same","original_before_record","final_same","final_before_source","final_hash","final_stale","canonical_address","canonical_alias","canonical_company","replayed_detail","proof_extra","caller_source"])("retains source and final independent review/canonical fencing %s",async k=>{const f=await setup(),e=f.entry,p=f.proof();if(k==="source_same")e.sourceReviewer.taskId=e.sourceReader.taskId;if(k==="source_before_capture")e.sourceReader.reviewedAt="2026-10-02T07:00:00Z";if(k==="original_same")e.originalReviews.independent.taskId=e.originalReviews.primary.taskId;if(k==="original_before_record")e.originalReviews.primary.reviewedAt="2026-09-29T00:00:00Z";if(k==="final_same")p.reviewer.taskId=p.reader.taskId;if(k==="final_before_source")p.reader.reviewedAt="2026-10-02T08:00:00Z";if(k==="final_hash")p.reader.evidenceSha256="0".repeat(64);if(k==="final_stale")p.reader.reviewedAt="2026-09-01T00:00:00Z";if(k==="canonical_address")f.context.addresses[0].addressLine1="5111 N SCOTTSDALE RD STE 200";if(k==="canonical_alias")(f.context.aliases as string[]).push("Other LLC");if(k==="canonical_company")f.company.name="Other LLC";if(k==="replayed_detail")f.row.detail="Changed final";if(k==="proof_extra")Object.assign(p,{address:"5111 N SCOTTSDALE RD STE 200"});if(k==="caller_source")Object.assign(p,{source:structuredClone(e.sources[0])});expect(()=>f.check(k.startsWith("final_")||["replayed_detail","proof_extra","caller_source"].includes(k)?p:undefined)).toThrow();});
});
