import { createHash } from "node:crypto";
import { describe, expect, it, vi } from "vitest";
import fixture from "../../test/fixtures/registry-official-api-alliance.json";
import { parseRegistryFinding, stableRegistryJson } from "./registryProfiles";
import type { RegistryOfficialApiEntry, RegistryOfficialApiTradeBundle } from "./registryOfficialApi";
import type { CompanyIdentityContext } from "@/lib/companyIdentity";
const sha=(s:string)=>createHash("sha256").update(s).digest("hex");
const now=new Date("2026-10-02T08:00:00Z"), reviewedAt="2026-10-02T07:59:00Z";
async function setup(){
 const f=structuredClone(fixture),entry=f.entry as RegistryOfficialApiEntry,context=f.context as CompanyIdentityContext;
 vi.resetModules();vi.doMock("./registryOfficialApiEntries.json",()=>({default:{version:1,entries:[entry]}}));
 const api=await import("./registryOfficialApi"),route=await import("./registryOfficialHistory");
 const row=parseRegistryFinding({...f.finding,registryProfile:f.finding.profile,source:"registry",kind:"ops_profile"},now);
 const proof=()=>{const bare={schema:"official_api_roles_v1" as const,entryId:entry.id,entrySha256:api.registryOfficialApiEntry(entry.id).sha256,canonicalIdentitySha256:entry.canonicalIdentitySha256};const evidenceSha256=api.registryOfficialApiEvidenceHash(row,bare);return {...bare,reader:{taskId:"/test/trade-primary",reviewedAt,evidenceSha256},reviewer:{taskId:"/test/trade-independent",reviewedAt,evidenceSha256}};};
 const check=()=>route.verifyRegistryOfficialHistory(row,proof(),f.company,context,now),rebind=()=>{entry.canonicalIdentitySha256=api.registryOfficialApiCanonicalHash(f.company,context);};
 const mutateRaw=(delta:Record<string,string|undefined>)=>{entry.source.rawRow=JSON.stringify({...JSON.parse(entry.source.rawRow),...delta});entry.source.rawRowSha256=sha(entry.source.rawRow);entry.source.byteLength=Buffer.byteLength(entry.source.rawRow);};
 return {...f,entry,context,api,route,row,proof,check,rebind,mutateRaw};
}
describe("finite official registered trade API association",()=>{
 it("accepts actual retained source with explicitly test-only final witnesses and unchanged physical facts",async()=>{const f=await setup(),before=JSON.stringify(f.row);expect(f.api.registryOfficialApiCanonicalHash(f.company,f.context)).toBe(f.entry.canonicalIdentitySha256);const v=f.check();expect(JSON.stringify(f.row)).toBe(before);expect(v.sourceIds).toEqual([`fmcsa:2087259:${f.proof().entrySha256}`,`co_sos:19961162961:${f.entry.nameBridge!.bundleSha256}`,"fda38cf9-8048-47c6-a33d-f3eea11389ec"]);expect(v.officialHistory).toMatchObject({companyEmailDomain:"alliance-leasing.com",canonicalAnchor:null,roleAddress:null,targetAddress:{role:"carrier_physical",addressLine1:"2075 S UNIVERSITY"},registeredTradeNameBridge:{tradeName:"ALLIANCE LEASING CORP.",canonicalAnchor:{addressLine1:"2075 S University Blvd # 289"}}});});
 it("needs opt-in and the dispatcher's exact reviewed bundle",async()=>{const f=await setup();expect(()=>f.api.verifyRegistryOfficialApi(f.row,f.proof(),f.company,f.context,now)).toThrow(/bundle/);delete f.entry.nameBridge;expect(f.check).toThrow(/operator conflict/);});
 it.each(["missing_alias","short_alias","other_alias","wrong_name","no_address","missing_unit","wrong_unit","missing_blvd","wrong_city","wrong_postal","untrusted_kind","no_source","duplicate_address"])("rejects canonical %s even when current hash is rebound",async k=>{const f=await setup();if(k==="missing_alias")f.context.aliases=[];if(k==="short_alias")f.context.aliases=["Alliance Leasing"];if(k==="other_alias")f.context.aliases.push("Another LLC");if(k==="wrong_name")f.company.name="Alliance";if(k==="no_address")f.context.addresses=[];if(k==="missing_unit")f.context.addresses[0].addressLine1="2075 S University Blvd";if(k==="wrong_unit")f.context.addresses[0].addressLine1="2075 S University Blvd # 290";if(k==="missing_blvd")f.context.addresses[0].addressLine1="2075 S University # 289";if(k==="wrong_city")f.context.addresses[0].city="Boulder";if(k==="wrong_postal")f.context.addresses[0].postalCode="80211";if(k==="untrusted_kind")Object.assign(f.context.addresses[0],{sourceKind:"sam_poc"});if(k==="no_source")f.context.addresses[0].sourceId="";if(k==="duplicate_address")f.context.addresses.push({...f.context.addresses[0]});f.rebind();expect(f.check).toThrow();});
 it.each([{dba_name:"ALLIANCE LEASING"},{legal_name:"ALLIANCE LEASING CORP"},{dot_number:"2087260"},{phy_street:"2075 S UNIVERSITY BLVD #289"},{email_address:"LEE@GMAIL.COM"},{email_address:"LEE@sub.alliance-leasing.com"},{email_address:"LEE@alliance-leasing.com.evil.test"}])("rejects changed full source %j",async delta=>{const f=await setup();f.mutateRaw(delta);expect(f.check).toThrow();});
 it.each(["bundleSha256","bundleId","entityId","tradeNameDocumentId","tradeName","extra","null","address_mode"])("rejects changed catalog relationship %s",async k=>{const f=await setup();if(k==="extra")Object.assign(f.entry.nameBridge!,{extra:true});else if(k==="null")Object.assign(f.entry,{nameBridge:null});else if(k==="address_mode")f.entry.anchor={mode:"address_role",role:"carrier_mailing",sourceId:f.context.addresses[0].sourceId};else Object.assign(f.entry.nameBridge!,{[k]:"wrong"});expect(f.check).toThrow();});
 it.each(["legal","trade","same_actor","early_source","bad_receipt","role","address"])("rejects counterfeit private bundle %s even with rehashed proposed bundle",async k=>{const f=await setup(),b=structuredClone(f.bundle);if(k==="legal")b.legalName="OTHER INC";if(k==="trade")b.tradeNames[0].name="ALLIANCE LEASING";if(k==="same_actor")b.sourceReviewer.taskId=b.sourceReader.taskId;if(k==="early_source")b.sourceReader.reviewedAt="2026-09-01T00:00:00Z";if(k==="bad_receipt")b.sourceReader.receiptSha256="bad";if(k==="role")b.anchor.role="registered_agent";if(k==="address")b.anchor.address.addressLine1="2075 S University Blvd #290";f.entry.nameBridge!.bundleSha256=sha(stableRegistryJson(b));expect(()=>f.api.verifyRegistryOfficialApi(f.row,f.proof(),f.company,f.context,now,b as RegistryOfficialApiTradeBundle)).toThrow();});
 it.each(["same_actor","early_final","changed_detail","changed_original","wrong_profile","future_final"])("rejects invalid final proof %s",async k=>{const f=await setup(),p=f.proof();if(k==="same_actor")p.reviewer.taskId=p.reader.taskId;if(k==="early_final")p.reader.reviewedAt="2026-10-01T11:00:00Z";if(k==="future_final")p.reviewer.reviewedAt="2027-01-01T00:00:00Z";if(k==="changed_detail")f.row.detail+="changed";if(k==="changed_original")f.row.evidence+="changed";if(k==="wrong_profile")f.row.profile.recordId="2087260";expect(()=>f.route.verifyRegistryOfficialHistory(f.row,p,f.company,f.context,now)).toThrow();});
});
