import { createHash } from "node:crypto";
import { beforeEach, describe, expect, it, vi } from "vitest";
const fetch = vi.hoisted(() => vi.fn());
vi.mock("@/lib/triggers/urlSafety", async original => ({ ...await original<typeof import("@/lib/triggers/urlSafety")>(), fetchPublicHttpText: fetch }));
import { htmlToVisibleText } from "@/lib/sources/siteDiscovery";
import { parseRegistryFinding, registryContentHash, stableRegistryJson } from "./registryProfiles";
import { parseRegistryWebsiteCorroboration, registryWebsiteEvidenceHash, registryWebsiteVerifier, type RegistryWebsiteCorroboration } from "./registryWebsite";
const now = new Date("2026-10-01T06:00:00Z"), sha = (s: string) => createHash("sha256").update(s).digest("hex");
const company = { name: "Brand Cargo", domain: "brand.com" }, context = { aliases: [] as string[], addresses: [], context: "" };
const raw = { dot_number: "1234567", dba_name: "BRAND CARGO CO", legal_name: "ORIGINAL OPERATOR LLC", phy_street: "123 N MAIN ST STE 4", phy_city: "AUSTIN", phy_state: "TX", phy_zip: "78701", phy_country: "US" };
const address = { addressLine1: "123 N Main St", addressLine2: "Suite 4", city: "Austin", state: "TX", postalCode: "78701", countryCode: "US" as const };
const relationship = 'These Terms of Use govern your access to and use of the website located at brand.com (the "Site"), operated by Original Operator LLC doing business as Brand Cargo Co. ("Brand Cargo," "we," "us," or "our").';
const contact = "Brand Cargo Co. 123 N Main St Suite 4 Austin TX 78701 USDOT 1234567";
const html = `<p>${relationship}</p><p>Contact ${contact}</p>`;
function row() { const identity = { legalName: raw.legal_name, addressLine1: raw.phy_street, city: raw.phy_city, state: raw.phy_state, postalCode: raw.phy_zip, countryCode: "US" }, sourceRow = { ...identity, usdot_number: raw.dot_number }, original = JSON.stringify(raw), evidence = JSON.stringify(sourceRow) + "\nOriginal public source row: " + original;
 return parseRegistryFinding({ source: "registry", kind: "ops_profile", companyId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa", internalId: "123", sourceUrl: "https://safer.fmcsa.dot.gov/query.asp?query_string=1234567", detail: "Dated registry facts.", evidence, registryProfile: { version: 1, dataset: "fmcsa", recordId: raw.dot_number, sourceAsOf: "2026-09-29", observedAt: now.toISOString(), identity, facts: [{ field: "usdot_number", value: raw.dot_number }], provenance: { sourceRow, rowSha256: sha(original), quote: evidence } } }, now); }
type Base = Omit<RegistryWebsiteCorroboration, "reader" | "reviewer">;
function base(body = html, overrides: Partial<Base> = {}): Base { const text = htmlToVisibleText(body); return { mode: "registry_dba_address", sourceUrl: "https://brand.com/terms", subject: "Brand Cargo Co.", quote: contact, quoteSha256: sha(contact), normalizedVisibleTextSha256: sha(text), address: { ...address }, operatorRelationship: { schema: "explicit_site_operator_dba_definition_v1", legalOperator: "Original Operator LLC", canonicalSubject: "Brand Cargo", quote: relationship, quoteSha256: sha(relationship) }, ...overrides }; }
function sign(r = row(), p = base()) { const evidenceSha256 = registryWebsiteEvidenceHash(r, p); return { ...p, reader: { taskId: "/test/reader", reviewedAt: now.toISOString(), evidenceSha256 }, reviewer: { taskId: "/test/reviewer", reviewedAt: now.toISOString(), evidenceSha256 } }; }
function page(body = html, finalUrl = "https://brand.com/terms") { return { body, finalUrl, contentType: "text/html", status: 200 }; }
async function verify(body = html, p = base(body), c = company, ctx = context, r = row()) { fetch.mockResolvedValue(page(body)); return registryWebsiteVerifier()(r, sign(r, p), c, ctx, now); }
beforeEach(() => { fetch.mockReset(); fetch.mockResolvedValue(page()); });
describe("explicit own-site operator, original DBA and defined canonical name", () => {
 it("binds both separate contiguous passages without changing source or canonical fields", async () => { const r = row(), original = JSON.stringify([r, company, context]), p = base(), v = await verify(html, p, company, context, r); expect(v.website?.binding).toBe("exact_original_registry_dba_defined_canonical_full_address"); expect(v.website?.operatorRelationship).toEqual(p.operatorRelationship); expect(JSON.stringify([r, company, context])).toBe(original); expect(fetch).toHaveBeenCalledTimes(1); });
 it("does not require the identifier beside the legal operator when the complete address independently matches", async () => { const body = html.replace("</p><p>", "</p><p>" + "Neutral prose. ".repeat(100) + "</p><p>"); expect((await verify(body)).method).toBe("official_website_corroboration"); });
 it.each(["Brand", "Brand Cargo West", "Brand Cargo LLC"])("rejects a different whole canonical name %s", async name => { await expect(verify(html, base(), { ...company, name })).rejects.toThrow(); });
 it.each(["Other LLC", "Original Operator Inc", "Brand Cargo LLC"])("preserves conflicting canonical aliases %s", async alias => { await expect(verify(html, base(), company, { ...context, aliases: [alias] })).rejects.toThrow(); });
 it.each(["Original Operator", "Original Operator Inc", "Global Original Operator LLC"])("requires the complete original operator %s", async legalOperator => { const quote = relationship.replace("Original Operator LLC", legalOperator), body = html.replace(relationship, quote), p = base(body); p.operatorRelationship = { ...p.operatorRelationship!, legalOperator, quote, quoteSha256: sha(quote) }; await expect(verify(body, p)).rejects.toThrow(); });
 it.each(["Brand Cargo", "Brand Cargo Company", "Brand Cargo Co. LLC"])("never clips or expands the full original DBA %s", async subject => { const p = base(); p.subject = subject; await expect(verify(html, p)).rejects.toThrow(); });
 it.each([
  relationship.replace('("Brand Cargo," "we," "us," or "our")', '("Other Brand," "we," "us," or "our")'),
  relationship.replace('("Brand Cargo," "we," "us," or "our")', ""),
  relationship.replace("operated by", "formerly operated by"),
  relationship.replace("operated by", "not operated by"),
  relationship.replace("doing business as", "affiliated with"),
  relationship.replace("Original Operator LLC doing", "Original Operator LLC's customer doing"),
  relationship.replace("brand.com", "other.com"),
  "Customer " + relationship,
  relationship + " Operated by Other LLC."
 ])("rejects unsupported or ambiguous relationship grammar %s", async quote => { const body = html.replace(relationship, quote), p = base(body); p.operatorRelationship = { ...p.operatorRelationship!, quote, quoteSha256: sha(quote) }; await expect(verify(body, p)).rejects.toThrow(); });
 it.each(["Customer example: ", "Not our operator: ", "Former relationship: "])("rejects an apparently exact statement in adverse page context %s", async prefix => { await expect(verify(prefix + html)).rejects.toThrow(); });
 it.each(["<p>Brand Cargo Co. (LLC)</p>", "<p>Customer Brand Cargo Co.</p>", "<p>Not Original Operator LLC</p>", "<p>Original Operator Inc</p>", "<p>Other Operator LLC doing business as Brand Cargo Co.</p>"])("does not exempt conflicting occurrences elsewhere %s", async extra => { await expect(verify(html + extra)).rejects.toThrow(); });
 it.each([" Operated by Other LLC.", " This operator statement is not current.", " This definition is false.", " The relationship is historical.", " Not the current operator.", " Owned by Other LLC.", " This is no longer true."])("rejects contradictory live-page context with unchanged selected definition %s", async suffix => { const body = html.replace(relationship, relationship + suffix), p = base(body); expect(p.operatorRelationship!.quote).toBe(relationship); await expect(verify(body, p)).rejects.toThrow("contradictory following context"); });
 it("rejects duplicated definitions", async () => { await expect(verify(html + `<p>${relationship}</p>`)).rejects.toThrow("duplicated"); });
 it("requires the relationship on the same page", async () => { await expect(verify(`<p>${contact}</p>`)).rejects.toThrow("missing"); });
 it("does not accept a concatenation of separated relationship pieces", async () => { const body = html.replace("doing business as", "END. Another unrelated statement. doing business as"); await expect(verify(body)).rejects.toThrow("missing"); });
 it("rejects an embedded clipped statement prefix", async () => { await expect(verify(html.replace(relationship, "Global" + relationship))).rejects.toThrow(); });
 it("does not treat a subsequent user-agreement condition as operator negation", async () => { expect((await verify(html.replace(relationship, relationship + " If you do not agree, do not use the site."))).method).toBe("official_website_corroboration"); });
 it.each([{ addressLine1: "124 N Main St" }, { addressLine2: "Suite 5" }, { addressLine2: undefined }, { city: "Dallas" }, { state: "CA" }, { postalCode: "78702" }, { countryCode: "CA" as const }])("preserves exact source address %j", async change => { const a = { ...address, ...change }, quote = `Brand Cargo Co. ${[a.addressLine1, a.addressLine2, a.city, a.state, a.postalCode].filter(Boolean).join(" ")}`, body = html.replace(contact, quote); await expect(verify(body, base(body, { address: a, quote, quoteSha256: sha(quote) }))).rejects.toThrow(); });
 it("rejects a conflicting labelled DOT anywhere", async () => { await expect(verify(html + "<p>USDOT 7654321</p>")).rejects.toThrow("conflicting labelled USDOT"); });
 it.each([undefined, "registry_identifier"] as const)("does not enable another mode %s", mode => { const r = row(), p = base(); p.mode = mode; if (mode) p.identifier = { kind: "usdot", value: raw.dot_number }; expect(() => parseRegistryWebsiteCorroboration(sign(r, p), r, now)).toThrow("operator relationship"); });
 it("rejects same reviewer and old or changed content witnesses", () => { const r = row(), p = sign(r); p.reviewer.taskId = p.reader.taskId; expect(() => parseRegistryWebsiteCorroboration(p, r, now)).toThrow("independent"); const q = sign(r); q.operatorRelationship!.canonicalSubject = "Other"; expect(() => parseRegistryWebsiteCorroboration(q, r, now)).toThrow(); const t = sign(r); r.detail = "Changed final detail"; expect(() => parseRegistryWebsiteCorroboration(t, r, now)).toThrow(); });
 it("rejects an expired relationship witness", () => { const r = row(), p = sign(r); p.reader.reviewedAt = "2020-01-01T00:00:00Z"; expect(() => parseRegistryWebsiteCorroboration(p, r, now)).toThrow(); });
 it("rejects stale full-page hash and wrong final host", async () => { const r = row(), p = sign(r); fetch.mockResolvedValueOnce(page(html + " changed")); await expect(registryWebsiteVerifier()(r, p, company, context, now)).rejects.toThrow("changed"); fetch.mockResolvedValueOnce(page(html, "https://other.com/terms")); await expect(registryWebsiteVerifier()(r, p, company, context, now)).rejects.toThrow("own-domain"); });
 it("keeps the prior DBA hash exact when relationship is absent", () => { const r = row(), p = base(); delete p.operatorRelationship; const legacy = { companyId: r.companyId, internalId: r.internalId, dataset: r.profile.dataset, recordId: r.profile.recordId, rowSha256: r.profile.provenance.rowSha256, ...p, dbaContent: { contentHash: registryContentHash(r.profile, r.sourceUrl, r.detail), evidenceSha256: sha(r.evidence), observedAt: r.profile.observedAt } }; expect(registryWebsiteEvidenceHash(r, p)).toBe(sha(stableRegistryJson(legacy))); });
});
